README.md
=> Explicitly note JSON Lines output format

wiktextract/data/en/other_subtitles.json
=> Update other_subtitles.json to include "Glyph origin"

README.md, tests/test_long.py, tests/test_utils.py, wiktextract/categories.py, wiktextract/clean.py, wiktextract/datautils.py, wiktextract/form_descriptions.py, wiktextract/inflection.py, wiktextract/linkages.py, wiktextract/page.py, wiktextract/pronunciations.py, wiktextract/template_override.py, wiktextract/thesaurus.py, wiktextract/translations.py, wiktextract/wiktionary.py, wiktextract/wiktwords.py
Changes in this pull request:
- Replace `--cache` option with `--db-path` in the `wiktwords` command.
- Remove namespace prefix checking because this is implemented in SQL query.
This pull request requires https://github.com/tatuylonen/wikitextprocessor/pull/41
=> Save page texts to SQLite database

wiktextract/categories.py, wiktextract/thesaurus.py, wiktextract/wiktionary.py, wiktextract/wiktwords.py
Fixes https://github.com/tatuylonen/wikitextprocessor/issues/45.
Also fix the error and improve the speed of `extract_namespace()` which is used in the `--modules-file` and `--templates-file` option.
=> Fix db connection error

README.md, tests/test_long.py, wiktextract/wiktionary.py, wiktextract/wiktwords.py
Save extracted pages to files code now moved to wikitextprocessor.
Fixes https://github.com/tatuylonen/wikitextprocessor/issues/47, requires https://github.com/tatuylonen/wikitextprocessor/pull/48.
=> Remove `capture_page()`

.github/workflows/test.yml, pyproject.toml
Same as https://github.com/tatuylonen/wikitextprocessor/pull/58. The test results from my forked repository: https://github.com/xxyzz/wiktextract/actions/runs/5195080494
=> Add test GitHub Actions

README.md, wiktextract/wiktwords.py
=> Update library usage example code in README file

tests/test_zh_example.py, tests/test_zh_linkage.py, wiktextract/extractor/share.py, wiktextract/extractor/zh/example.py, wiktextract/extractor/zh/linkage.py, wiktextract/extractor/zh/page.py, wiktextract/extractor/zh/thesaurus.py
- Move extract example code to a new file.
- Handle more example and linkage case.
- Add two Chinese extractor tests.
=> Some changes to the Chinese Wiktionary extractor code

tests/test_page.py, wiktextract/extractor/en/page.py
Some word entries only have a single or multiple `zh-see` templates under the language subtitle to indicate the word is a variant of another Chinese character or word.
Fixes #287
=> Treat `zh-see` template as redirect page

.github/workflows/test.yml
Same as https://github.com/tatuylonen/wikitextprocessor/pull/71 but the branch name changed to `master`.
=> Upload test coverage HTML files to GitHub Pages

tests/test_zh_inflection.py, tests/test_zh_translation.py, wiktextract/extractor/zh/example.py, wiktextract/extractor/zh/gloss.py, wiktextract/extractor/zh/headword_line.py, wiktextract/extractor/zh/inflection.py, wiktextract/extractor/zh/linkage.py, wiktextract/extractor/zh/page.py, wiktextract/extractor/zh/pronunciation.py, wiktextract/extractor/zh/thesaurus.py, wiktextract/extractor/zh/translation.py, wiktextract/translations.py
- Add Chinese Wiktionary ja-i template test
- Parse Chinese Wiktionary translation list
=> Parse Chinese Wiktionary translation list

tests/test_zh_example.py, tests/test_zh_gloss.py, tests/test_zh_headword.py, tests/test_zh_linkage.py, tests/test_zh_translation.py, wiktextract/data/zh/linkage_subtitles.json, wiktextract/datautils.py, wiktextract/extractor/zh/gloss.py, wiktextract/extractor/zh/linkage.py, wiktextract/extractor/zh/page.py, wiktextract/extractor/zh/translation.py
And insert translation data to sense dictionary that has similar gloss.
=> Support `see translation subpage` template

README.md, pyproject.toml, tests/test_long.py, wiktextract/config.py, wiktextract/extractor/en/thesaurus.py, wiktextract/extractor/zh/thesaurus.py, wiktextract/thesaurus.py, wiktextract/wiktionary.py, wiktextract/wiktwords.py, wiktextract/wxr_context.py
Requires https://github.com/tatuylonen/wikitextprocessor/pull/88
=> Support multiprocessing on macOS and Windows

pyproject.toml, tests/test_fr_form_line.py, wiktextract/extractor/en/thesaurus.py, wiktextract/extractor/fr/form_line.py, wiktextract/extractor/fr/gloss.py, wiktextract/extractor/fr/inflection.py, wiktextract/extractor/fr/page.py, wiktextract/extractor/share.py, wiktextract/extractor/zh/example.py, wiktextract/extractor/zh/gloss.py, wiktextract/extractor/zh/headword_line.py, wiktextract/extractor/zh/inflection.py, wiktextract/extractor/zh/linkage.py, wiktextract/extractor/zh/page.py, wiktextract/extractor/zh/pronunciation.py, wiktextract/extractor/zh/translation.py, wiktextract/page.py
I didn't change the English extractor code because it creates `WikiNode` at here: https://github.com/tatuylonen/wiktextract/blob/205c4a2d88c27113f0117e0095f466605976af81/wiktextract/page.py#L80
=> Use new `WikiNode` select node method and subclass attribute

wiktextract/thesaurus.py
Inside each worker process, `insert_thesaurus_term()` runs a few SQL queries before committing, move it to the main Pool loop to avoid racing.
=> Fix database locked error when inserting thesaurus data

tests/test_fr_form_line.py, tests/test_fr_inflection.py, wiktextract/extractor/fr/form_line.py, wiktextract/extractor/fr/gloss.py, wiktextract/extractor/fr/inflection.py, wiktextract/extractor/fr/page.py, wiktextract/extractor/fr/pronunciation.py
- Fix error when templates are used in "exemple" template, requires https://github.com/tatuylonen/wikitextprocessor/pull/103
- Fix error in `process_pron_list_item()`
- A new extract inflection table function
=> Update French Wiktionary code

tests/test_fr_pronunciation.py, tests/test_fr_translation.py, wiktextract/extractor/fr/page.py, wiktextract/extractor/fr/pronunciation.py, wiktextract/extractor/fr/translation.py
When the section contsins audio file data but doesn't have IPA data.
=> Don't return empty list from `process_pron_list_item()`

overrides/zh.json
Requires https://github.com/tatuylonen/wikitextprocessor/pull/112
=> Add more page data to Chinese Wiktionary override JSON file

json_schema/zh.json, tests/test_zh_descendant.py, wiktextract/data/zh/linkage_subtitles.json, wiktextract/data/zh/other_subtitles.json, wiktextract/extractor/ruby.py, wiktextract/extractor/zh/descendant.py, wiktextract/extractor/zh/linkage.py, wiktextract/extractor/zh/page.py
This pull request adds a new "descendants" property to the Chinese Wiktionary JSON schema. Unlink the English JSON uses a depth number, the new JSON data uses a self-reference structure to represent the depth.
=> Extract Chinese Wiktionary descendant data

src/wiktextract/extractor/zh/linkage.py
This line was missed in the last commit.
=> Change linakge property "lang" to "lang_name" in "zh/linkage.py"

.github/workflows/container.yml
This line should be added in the last pr #399
=> Don't skip publish container action when triggered manually

src/wiktextract/extractor/en/page.py, src/wiktextract/wiktwords.py
Removed in https://github.com/tatuylonen/wikitextprocessor/pull/157
=> Replace removed `Wtp.read_by_title()` method

src/wiktextract/extractor/es/etymology.py, src/wiktextract/extractor/es/example.py, src/wiktextract/extractor/es/gloss.py, src/wiktextract/extractor/es/linkage.py, src/wiktextract/extractor/es/models.py, src/wiktextract/extractor/es/page.py, src/wiktextract/extractor/es/pronunciation.py, src/wiktextract/extractor/es/sense_data.py, src/wiktextract/extractor/es/translation.py, tests/test_es_etymology.py, tests/test_es_example.py, tests/test_es_gloss.py, tests/test_es_linkage.py, tests/test_es_page.py, tests/test_es_pronunciation.py, tests/test_es_translation.py
As promised, here's my first contribution! I tried to follow already-established patterns and style. Please, let me know about any improvements I can make, as small as it could be, I like doing things the right way.
=> Spanish etymology extraction

src/wiktextract/extractor/fr/linkage.py, tests/test_fr_linkage.py
Links also could be used in lists of this block.
=> Extract links in "Dérivés dans d’autres langues" section

src/wiktextract/extractor/fr/inflection.py, tests/test_fr_inflection.py
These templates use the data wikitext for column header
=> Extract "en-adj" inflection tables in French Wiktionary

.github/workflows/test.yml, .github/workflows/test_schedule.yml, tools/test_schedule.py
Trigger test action if wikitextprocessor is updated after the last test.
=> Add daily schedule test action

src/wiktextract/extractor/fr/conjugation.py, src/wiktextract/extractor/fr/etymology.py, src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/zh/linkage.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/pronunciation.py, src/wiktextract/extractor/zh/translation.py, tests/test_fr_conj.py
Finally get this partially done after fixing wikitextprocessor bugs discovered when working on this pr.
=> Extract French Conjugaison pages

pyproject.toml, src/wiktextract/extractor/de/example.py, src/wiktextract/extractor/de/gloss.py, src/wiktextract/extractor/de/linkage.py, src/wiktextract/extractor/de/models.py, src/wiktextract/extractor/de/page.py, src/wiktextract/extractor/de/pronunciation.py, src/wiktextract/extractor/de/translation.py, src/wiktextract/extractor/es/example.py, src/wiktextract/extractor/es/gloss.py, src/wiktextract/extractor/es/models.py, src/wiktextract/extractor/es/page.py, src/wiktextract/extractor/es/pronunciation.py, tests/test_de_example.py, tests/test_de_gloss.py, tests/test_de_linkages.py, tests/test_de_page.py, tests/test_de_pronunciation.py, tests/test_de_translation.py, tests/test_es_etymology.py, tests/test_es_example.py, tests/test_es_gloss.py, tests/test_es_page.py, tests/test_es_pronunciation.py, tests/test_es_translation.py, tools/generate_schema.py
And use more strict configurations.
=> Remove Optional types in de and es pydantic models

src/wiktextract/extractor/ru/linkage.py, src/wiktextract/extractor/ru/models.py, tests/test_ru_linkage.py
=> Extract linkage tags for ru edition

src/wiktextract/extractor/ru/example.py, src/wiktextract/extractor/ru/gloss.py, src/wiktextract/extractor/ru/inflection.py, src/wiktextract/extractor/ru/linkage.py, src/wiktextract/extractor/ru/models.py, src/wiktextract/extractor/ru/page.py, src/wiktextract/extractor/ru/pronunciation.py, src/wiktextract/extractor/ru/translation.py, tests/test_ru_inflection.py
Inflection tables are so difficult to process...
=> Extract forms table from expanded "прил*" template

src/wiktextract/data/fr/pos_subtitles.json, src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/models.py, src/wiktextract/extractor/fr/page.py, tests/test_fr_gloss.py
=> Find alternative form of the "typographic variant" POS word

src/wiktextract/data/zh/pos_subtitles.json, src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/zh/headword_line.py, src/wiktextract/extractor/zh/models.py, src/wiktextract/extractor/zh/page.py, tests/test_fr_gloss.py, tests/test_zh_descendant.py, tests/test_zh_gloss.py, tests/test_zh_headword.py
=> Handle zh edition soft redirect templates and gloss sentence only pages

src/wiktextract/extractor/fr/models.py, src/wiktextract/extractor/zh/models.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/translation.py, tests/test_zh_gloss.py, tests/test_zh_headword.py, tests/test_zh_translation.py
There are too many translation list layouts in Chinese Wiktionary, this pr only covers part of them.
Issue #471
=> Improve zh edition translation code

src/wiktextract/extractor/fr/etymology.py, src/wiktextract/extractor/fr/gloss.py, tests/test_fr_gloss.py
also add "alt-of" tag
Issue #467
=> Add "alt_of" field for fr edition's "variante * de" templates

src/wiktextract/extractor/ru/models.py, src/wiktextract/extractor/ru/page.py
Use the same POS types as the en edition. Issue #469
=> Update ru edition POS types and tags

src/wiktextract/extractor/ru/page.py
I forgot to convert list to str.
=> Fix TypeError in ru extractor

src/wiktextract/extractor/ru/page.py
Fix two errors added from my last pr.
=> Fix exceptions in ru extractor

src/wiktextract/extractor/ru/gloss.py, src/wiktextract/extractor/ru/page.py, tests/test_ru_gloss.py, tests/test_ru_page.py
=> Find POS in ru edition nonstandard format pages 

src/wiktextract/extractor/fr/linkage.py, src/wiktextract/extractor/fr/models.py, src/wiktextract/extractor/fr/pronunciation.py, tests/test_fr_pronunciation.py
Should be less garbage tags, also make `Linkage.word` is required field.  Fix the ":" tag mentioned in comment: https://github.com/tatuylonen/wiktextract/issues/489#issuecomment-1926359174
=> Update fr edition linkage and pronounciation tags code

src/wiktextract/extractor/fr/linkage.py, src/wiktextract/extractor/fr/pronunciation.py, src/wiktextract/extractor/share.py, tests/test_fr_linkage.py, tests/test_fr_pronunciation.py
=> Reduce incorrect linkage tags in fr edition

src/wiktextract/extractor/fr/form_line.py, src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/inflection.py, tests/test_fr_gloss.py
- Remove some tags, issue #489
- Fix empty gloss text in pages use template "variante * de"
=> Remove some fr edition tags

.github/workflows/test.yml
3.12 tests should be faster now.
=> Add `COVERAGE_CORE=sysmon` environment variable to test action job

src/wiktextract/extractor/fr/gloss.py, tests/test_fr_gloss.py
Page: https://fr.wiktionary.org/wiki/advena
=> Extract example translation list in some fr edition pages

src/wiktextract/extractor/fr/etymology.py, src/wiktextract/extractor/fr/page.py, tests/test_fr_etymology.py, tests/test_fr_page.py
Usually they are at the same level
=> Extract POS under the etymology section in some fr edition pages

src/wiktextract/extractor/fr/etymology.py, src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/inflection.py, src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/fr/section_types.py, src/wiktextract/wiktionary.py, tests/test_fr_gloss.py
Fix most missing "pos" and "glosses" fields errors.
=> Fix some check JSON errors in the fr edition

src/wiktextract/extractor/ru/page.py, tests/test_ru_page.py
and use "unknown" as the default POS type
=> Extract POS type from ru edition's "suffix" template

src/wiktextract/extractor/fr/inflection.py, src/wiktextract/extractor/fr/linkage.py, src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/fr/tags.py, src/wiktextract/extractor/fr/translation.py, tests/test_fr_translation.py
All JSON check warnings should be fixed.
=> Fix exceptions and warnings in fr edition and convert translation raw tags

src/wiktextract/extractor/de/gloss.py, src/wiktextract/extractor/de/models.py, src/wiktextract/extractor/de/page.py, src/wiktextract/extractor/de/section_titles.py, src/wiktextract/extractor/de/translation.py, tests/test_de_gloss.py, tests/test_de_page.py
More changes are needed for these files, code handle POS title template and gloss templates could be simplified.
=> Some changes for de edition's `page.py` and `gloss.py` file

src/wiktextract/extractor/de/gloss.py, src/wiktextract/extractor/de/models.py, src/wiktextract/extractor/de/page.py, tests/test_de_gloss.py, tests/test_de_page.py
I also updated the [mediawiki_langcodes](https://github.com/xxyzz/mediawiki_langcodes/releases/tag/v0.2.3) package to include some German language names, but upload new package to pypi.org is [disabled today](https://status.python.org/incidents/dc9zsqzrs0bv).
=> Simplify de editon's `page.py` and `gloss.py` file

src/wiktextract/extractor/de/models.py, src/wiktextract/extractor/de/page.py, tests/test_de_page.py
2934 pages use this template to list transcription words.
=> Handle de edition's "Ähnlichkeiten Umschrift" template

src/wiktextract/extractor/de/tags.py, src/wiktextract/extractor/de/translation.py, tests/test_de_translation.py
- parse the translation list item nodes created from template argument
- get language name from expanded template
- get language code from template name and template argument
- extract data in the "Dialekttabelle" template argument
- extract "Üxx4" template
- translate raw tags
=> Improve de edition extract translation code

src/wiktextract/extractor/de/translation.py, tests/test_de_translation.py
Some template arguments might contain wikitext.
=> Fix pydantic validation errors in de edition translation code

src/wiktextract/datautils.py, src/wiktextract/extractor/en/page.py, src/wiktextract/wiktionary.py
Turned out there were a ton of invalid tags that were slipping through. Instead of separating valid tags from invalid ones everywhere in the code, let's see if modifying data_append works out. Tests pass.
=> Check if tags are valid in data_append

src/wiktextract/extractor/zh/page.py, src/wiktextract/wiktwords.py
new `quiet` argument is added in https://github.com/tatuylonen/wikitextprocessor/pull/273
=> Pass --quiet to Wtp.__init__()

src/wiktextract/datautils.py, src/wiktextract/extractor/en/page.py
Instead of doing tag validation in a utility function, do it recursively at the end of parsing a page.
=> Tagvalidation

src/wiktextract/extractor/es/page.py, src/wiktextract/extractor/es/translation.py, src/wiktextract/extractor/zh/linkage.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/pronunciation.py, tests/test_es_translation.py, tests/test_zh_pronunciation.py
Use HTML tags and less hard coded strings.
=> Simplify zh edition's pronunciation code

README.md, src/wiktextract/extractor/zh/example.py, src/wiktextract/extractor/zh/models.py, tests/test_zh_example.py
Requires https://github.com/tatuylonen/wikitextprocessor/pull/278
=> Use `str` type `Example.text` field for zh edition's pydantic model

src/wiktextract/extractor/fr/form_line.py, src/wiktextract/extractor/fr/pronunciation.py, tests/test_fr_pronunciation.py
=> [fr] expand "cmn-pron" template to lists

src/wiktextract/extractor/de/page.py, src/wiktextract/extractor/de/translation.py, src/wiktextract/wiktionary.py
the last check JSON error in de edition
=> [de] fix missing translation language name error in page "Synagoge"

src/wiktextract/extractor/ru/etymology.py, src/wiktextract/extractor/ru/inflection.py, src/wiktextract/extractor/ru/models.py, src/wiktextract/extractor/ru/page.py, src/wiktextract/extractor/ru/tags.py, tests/test_ru_inflection.py
=> [ru] extract noun inflection table expanded from "сущ " templates

src/wiktextract/extractor/de/etymology.py, src/wiktextract/extractor/de/models.py, src/wiktextract/extractor/de/page.py
=> [de] extract etymology("Herkunft") section text

src/wiktextract/extractor/ru/gloss.py, src/wiktextract/extractor/ru/models.py, src/wiktextract/extractor/ru/page.py, src/wiktextract/extractor/ru/section_titles.py, tests/test_ru_gloss.py
256 pages use this template for gloss and linkage
=> [ru] process "значение" gloss template

src/wiktextract/extractor/ru/inflection.py, src/wiktextract/extractor/ru/tags.py, tests/test_ru_inflection.py
From page "вода", the only featured article in Russian Wiktionary.
=> [ru] extract the "падежи cu" table template

src/wiktextract/extractor/es/inflection.py, src/wiktextract/extractor/es/models.py, src/wiktextract/extractor/es/page.py, src/wiktextract/extractor/es/tags.py, src/wiktextract/extractor/fr/inflection.py, tests/test_es_forms.py
Verb form tables are more complex.
Ignore some evil templates like this one: https://es.wiktionary.org/wiki/Plantilla:inflect.en.adj
=> [es] extract noun and adj form tables

src/wiktextract/extractor/ru/linkage.py, src/wiktextract/extractor/ru/page.py, tests/test_ru_linkage.py
this section contains derived phrases, Google translate says the title is "Phraseologisms and stable combinations".
=> [ru] extract "Фразеологизмы и устойчивые сочетания" section

src/wiktextract/extractor/fr/etymology.py, src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/models.py, src/wiktextract/extractor/fr/page.py, tests/test_fr_etymology.py
This section is under the "Étymologie" section and contains some example sentences.
=> [fr] extract "Attestations historiques" section

src/wiktextract/extractor/fr/form_line.py, src/wiktextract/extractor/fr/tags.py
and ignore some missing gender or number templates
=> [fr] translate some form line and sense tags

src/wiktextract/extractor/fr/etymology.py, tests/test_fr_etymology.py
must check the link node has `str` type id
=> [fr] fix `AttributeError` in `find_pos_in_etymology_list()`

src/wiktextract/extractor/zh/page.py
previous code only add "zh-forms" data to the last POS section data
Example page: https://zh.wiktionary.org/wiki/機車
=> [zh] extract "zh-forms" template before extracting other sections

src/wiktextract/extractor/fr/linkage.py, tests/test_fr_linkage.py
the second link node shouldn't overwrite the first linkage word
=> [fr] fix extract linkage list code in page "alcool"

src/wiktextract/extractor/ru/pronunciation.py
this template seems mostly used for non-Russian words
=> [ru] extract audio file URLs from "медиа" template

src/wiktextract/extractor/es/gloss.py, src/wiktextract/extractor/es/page.py, tests/test_es_gloss.py
- remove `breakpoint`
- remove empty gloss data
- add extra form-of word when "pronominal" parameter is used
=> [es] fix remaining issues with form-of templates

src/wiktextract/extractor/zh/gloss.py, tests/test_zh_gloss.py
This template puts form word in the second `<i>` tag
=> [zh] fix form-of data for "es-verb form of" template

src/wiktextract/extractor/es/linkage.py
caused by a typo in this page: "notae" invalid template parameter
=> [es] fix `ValueError` exception in page "metegol"

src/wiktextract/extractor/en/page.py, tests/test_page.py
and "ja-see" template, silence many check JSON errors.
=> [en] add empty gloss and "no-gloss" tag for "zh-see" template

src/wiktextract/extractor/fr/models.py
silence mypy "Missing named argument" errors
=> [fr] use the `default` keyword of `pydantic.Field()`

src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/fr/pronunciation.py, tests/test_fr_gloss.py, tests/test_fr_page.py, tests/test_fr_pronunciation.py
Only add new `WordEntry` for POS section data in `process_pos_block()`.
=> [fr] reduce empty gloss data

src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/linkage.py, src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/fr/section_types.py, tests/test_fr_gloss.py, tests/test_fr_linkage.py
Pages have "no-gloss" tag have all kinds of non-standard(low quality) wikitext structure.
=> [fr] extract more linkage and pos section data

src/wiktextract/extractor/zh/page.py, tests/test_zh_gloss.py, tests/test_zh_linkage.py
Most "no-gloss" tag pages really don't have gloss at all...
=> [zh] extract data from low quality German pages

src/wiktextract/extractor/ru/gloss.py, src/wiktextract/extractor/ru/page.py
Like zh edition, tons of empty pages created by bot.
=> [ru] changes for low quality pages

src/wiktextract/extractor/en/page.py, src/wiktextract/extractor/en/thesaurus.py, src/wiktextract/form_descriptions.py, tests/test_head.py
=> [en] combine tags for pages have more than one head line

src/wiktextract/extractor/pl/pos.py, src/wiktextract/extractor/pl/tags.py
in page "Pomoc:Skróty używane w Wikisłowniku"
=> [pl] translate some tags and topics data start with "a" and b"

src/wiktextract/extractor/fr/conjugation.py, src/wiktextract/extractor/fr/etymology.py, src/wiktextract/extractor/fr/form_line.py, src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/linkage.py, src/wiktextract/extractor/fr/note.py, src/wiktextract/extractor/fr/pronunciation.py, src/wiktextract/extractor/fr/section_types.py, src/wiktextract/extractor/fr/translation.py
This template has a "note" subtitle node above tables
=> [fr] find tables under level 3 title in "fr-conj-1-ier" template

src/wiktextract/extractor/ja/example.py, tests/test_ja_example.py
=> [ja] extract example ref in `<small>` tag

src/wiktextract/extractor/ja/sound.py, tests/test_ja_sound.py
wikitext could be used in template argument
=> [ja] fix pydantic error in page "lice"

src/wiktextract/extractor/pl/inflection.py, src/wiktextract/extractor/pl/tags.py, tests/test_pl_inflection.py
Complex table, has a few more forms than en edition.
=> [pl] extract verb inflection template "odmiana-czasownik-polski"

src/wiktextract/extractor/pl/linkage.py, src/wiktextract/extractor/pl/pos.py, src/wiktextract/extractor/pl/sound.py, src/wiktextract/extractor/pl/tags.py, tests/test_pl_gloss.py, tests/test_pl_linkage.py, tests/test_pl_sound.py
Handle more layouts, not sure they are common or rare.
=> [pl] impove linkage, pos and sound section code

src/wiktextract/extractor/pl/inflection.py, tests/test_pl_inflection.py
This template could use tag template in arguments, previous code expands template to HTML table but it's tricky to distinguish word and tag.
=> [pl] extract "odmiana-rzeczownik-polski" template parameters

src/wiktextract/extractor/pl/inflection.py, tests/test_pl_inflection.py
HTML nodes in template args are parsed as text
=> [pl] remove nodes after `<ref>` tag in noun forms template argument

src/wiktextract/extractor/ru/page.py
this section only has one link node
=> [ru] extract латиница(romanization) section

src/wiktextract/extractor/zh/descendant.py, src/wiktextract/extractor/zh/etymology.py, src/wiktextract/extractor/zh/gloss.py, src/wiktextract/extractor/zh/headword_line.py, src/wiktextract/extractor/zh/linkage.py, src/wiktextract/extractor/zh/models.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/pronunciation.py, src/wiktextract/extractor/zh/tags.py, src/wiktextract/extractor/zh/thesaurus.py, tests/test_zh_gloss.py, tests/test_zh_linkage.py
Tidy up my old terrible code...
=> [zh] improve extract linkage section code

src/wiktextract/extractor/fr/linkage.py, src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/fr/pronunciation.py, src/wiktextract/extractor/fr/translation.py, src/wiktextract/extractor/ja/page.py, tests/test_fr_conj.py, tests/test_fr_etymology.py, tests/test_fr_form_line.py, tests/test_fr_gloss.py, tests/test_fr_inflection.py, tests/test_fr_linkage.py, tests/test_fr_note.py, tests/test_fr_page.py, tests/test_fr_pronunciation.py, tests/test_fr_translation.py
`process_linkage_list()` grows a few lines longer...
=> [fr] call `parse_section()` recursively and remove "réf" template as tag data

src/wiktextract/extractor/zh/descendant.py, src/wiktextract/extractor/zh/linkage.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/section_titles.py, src/wiktextract/extractor/zh/tags.py, tests/test_zh_descendant.py
"派生詞" could be linkage or descendant section
=> [zh] extract "cjvk" and "desctree" templates in descendant section

src/wiktextract/extractor/zh/descendant.py, src/wiktextract/extractor/zh/linkage.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/thesaurus.py, tests/test_zh_descendant.py, tests/test_zh_linkage.py
level 3 section data should be added to all previous POS section data, not prefect but should cover most pages
=> [zh] add level 3 linkage and descendant section data to all pos data

src/wiktextract/extractor/de/example.py, src/wiktextract/extractor/de/form.py, src/wiktextract/extractor/de/gloss.py, src/wiktextract/extractor/de/inflection.py, src/wiktextract/extractor/de/linkage.py, src/wiktextract/extractor/de/models.py, src/wiktextract/extractor/de/page.py, src/wiktextract/extractor/de/pronunciation.py, src/wiktextract/extractor/de/section_titles.py, src/wiktextract/extractor/de/translation.py, src/wiktextract/extractor/de/utils.py, tests/test_de_example.py, tests/test_de_forms.py, tests/test_de_gloss.py, tests/test_de_linkages.py, tests/test_de_page.py, tests/test_de_pronunciation.py, tests/test_de_translation.py, tests/test_de_utils.py
And match more sense index patterns.
=> [de] improve example and linkage section code, extract forms sections

src/wiktextract/extractor/ja/sound.py, tests/test_ja_sound.py
Should expand template args...
Requires https://github.com/tatuylonen/wikitextprocessor/pull/302
=> [ja] fix `AttributeError` exceptions in `process_sound_template()`

src/wiktextract/extractor/ja/etymology.py, src/wiktextract/extractor/ja/example.py, src/wiktextract/extractor/ja/linkage.py, src/wiktextract/extractor/ja/models.py, src/wiktextract/extractor/ja/page.py, src/wiktextract/extractor/ja/section_titles.py, tests/test_ja_example.py, tests/test_ja_linkage.py
=> [ja] improve linkage, etymology, example section code

src/wiktextract/extractor/en/example.py
=> [en] return `ExampleData` from `extract_template_ja_usex()`

src/wiktextract/extractor/en/page.py
xxyzz has recently implemented some code for extracting Chinese and Japanese examples, and quotations, which is used as a bypass in [en] page.py that returns early if it find anything good. Some of the old code was still around, and this cleans some of it that should 100% be obsolete, but some, like the ruby-detection stuff is left as is, in case we come across something that isn't taken care of by xxyzz's implementation.
=> [en] Remove some unused code from page.py

src/wiktextract/extractor/zh/example.py, src/wiktextract/extractor/zh/gloss.py, src/wiktextract/extractor/zh/models.py, src/wiktextract/extractor/zh/tags.py, tests/test_zh_etymology.py, tests/test_zh_example.py, tests/test_zh_gloss.py
zh-x template code in en extractor also need update, I'll do that later, maybe tomorrow...
=> [zh] improve extract gloss and example data code 

src/wiktextract/extractor/en/page.py
Commonly used in Chinese Chengyu pages, extract them to the new "etymology_examples" field, same as zh edition.
Example pages: [一毛不拔](https://en.wiktionary.org/wiki/一毛不拔), [焚膏繼晷](https://en.wiktionary.org/wiki/焚膏繼晷)
zh edition code also have some examples in tests.
=> [en] extract "zh-x" example template in etymology section

src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/fr/tags.py, tests/test_fr_gloss.py, tests/test_fr_inflection.py
=> [fr] extract "zh-exemple" example template inside gloss list

src/wiktextract/extractor/ru/pronunciation.py
template args could have magic words like `PAGENAME`
=> [ru] fix `AttributeError` exception in page "opgave" and "denaske"

src/wiktextract/extractor/fr/conjugation.py
unless the template has "sél" parameter that is not "1" or the first tab text is "Conjugaison active". For example, page "Conjugaison:français/abattre" in previous test.
But some pages like "Conjugaison:français/harceler" and "Conjugaison:français/bayer" should extract all tabs.
=> [fr] extract tables in all "Onglets conjugaison" template tabs

src/wiktextract/extractor/ru/page.py, src/wiktextract/extractor/ru/pronunciation.py
some pages use a list but some use a single link node
=> [ru] extract "омофоны"(homophone) sections

src/wiktextract/data/ko/config.json, src/wiktextract/extractor/ja/section_titles.py, src/wiktextract/extractor/ko/models.py, src/wiktextract/extractor/ko/page.py, src/wiktextract/extractor/ko/pos.py, src/wiktextract/extractor/ko/section_titles.py, tests/test_ko_gloss.py, tests/test_ru_sound.py
=> [ko] add Korean edition extractor

src/wiktextract/extractor/de/example.py, tests/test_de_example.py
some pages have an empty arg at the end
=> [de] fix `AttributeError: 'int' object has no attribute 'lower'`

src/wiktextract/extractor/nl/models.py, src/wiktextract/extractor/nl/pos.py, tests/test_nl_gloss.py
Unlike other editions use number for sense index, nl edition uses letters: [A], [B].
=> [nl] extract tag templates in gloss list, "-l-" gender templates and sense index data

src/wiktextract/extractor/ko/models.py, src/wiktextract/extractor/ko/page.py, src/wiktextract/extractor/ko/pos.py, src/wiktextract/extractor/ko/section_titles.py, src/wiktextract/extractor/ko/sound.py, tests/test_ko_sound.py
Sound templates could under language title, pos title or pronunciation title, this chaotic layout is worse then ja edition.
=> [ko] extract some sound templates

src/wiktextract/extractor/de/page.py, src/wiktextract/extractor/es/page.py, src/wiktextract/extractor/fr/page.py, src/wiktextract/extractor/ja/page.py, src/wiktextract/extractor/ko/example.py, src/wiktextract/extractor/ko/linkage.py, src/wiktextract/extractor/ko/models.py, src/wiktextract/extractor/ko/page.py, src/wiktextract/extractor/ko/pos.py, src/wiktextract/extractor/ko/section_titles.py, src/wiktextract/extractor/pl/page.py, src/wiktextract/extractor/ru/page.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/page.py, tests/test_ko_gloss.py, tests/test_ko_linkage.py
=> [ko] extract note list and linkage list

src/wiktextract/data/es/config.json, src/wiktextract/extractor/es/models.py, src/wiktextract/extractor/es/pronunciation.py, tests/test_es_pronunciation.py
- set "phonos" tag to "*"
- extract category link in "pron-graf" template
=> [es] extract "silabación" to "hyphenation" field

src/wiktextract/extractor/nl/descendant.py, src/wiktextract/extractor/nl/etymology.py, src/wiktextract/extractor/nl/linkage.py, src/wiktextract/extractor/nl/models.py, src/wiktextract/extractor/nl/page.py, src/wiktextract/extractor/nl/spelling_form.py, src/wiktextract/extractor/nl/translation.py, tests/test_nl_descendant.py, tests/test_nl_etymology.py, tests/test_nl_spelling_form.py, tests/test_nl_translation.py
Most common sections except inflection sections are extracted.
=> [nl] extract new sections and fix pydantic errors

src/wiktextract/extractor/nl/inflection.py, src/wiktextract/extractor/nl/models.py, src/wiktextract/extractor/nl/pos.py, src/wiktextract/extractor/nl/tags.py, tests/test_nl_gloss.py, tests/test_nl_inflection.py
=> [nl] extract adj and verb forms table, and "eng-onv-d" form-of template

src/wiktextract/extractor/ko/etymology.py, src/wiktextract/extractor/ko/models.py, src/wiktextract/extractor/ko/page.py, src/wiktextract/extractor/ko/pos.py, src/wiktextract/extractor/ko/sound.py, src/wiktextract/extractor/ko/tags.py, tests/test_ko_etymology.py, tests/test_ko_gloss.py, tests/test_ko_sound.py
=> [ko] improve etymology and pos section code

src/wiktextract/tags.py
=> [en] Tags: add 'Benglish' to uppercase_tags

src/wiktextract/tags.py
see https://github.com/tatuylonen/wiktextract/issues/906
=> Added "Bangladesh" and "Hinglish" to uppercase_tags

src/wiktextract/extractor/fr/tags.py, src/wiktextract/extractor/ko/tags.py
example page "good" puts gloss list in linkage section
=> [ko] fix exception in low quality pages

src/wiktextract/extractor/ru/page.py, tests/test_ru_page.py, tests/test_ru_sound.py
=> [ru] extract stressed form in "з" template

src/wiktextract/wiktwords.py
I forget en code don't use pydantic in my last pr
=> Add "en" to "--edition" options

src/wiktextract/extractor/es/conjugation.py, tests/test_es_conj.py
=> [es] fix number tags of the last row in "es.v.conj" template table

src/wiktextract/extractor/en/inflectiondata.py
Fixes #973
This apparently broke the table pretty badly.
=> [en] Inflection data addition for Assyrian Neo-Aramaic

src/wiktextract/extractor/th/alt_form.py, src/wiktextract/extractor/th/models.py, src/wiktextract/extractor/th/page.py, src/wiktextract/extractor/th/pos.py, src/wiktextract/extractor/th/section_titles.py, tests/test_it_etymology.py, tests/test_it_example.py, tests/test_it_forms.py, tests/test_it_gloss.py, tests/test_it_linkage.py, tests/test_it_sound.py, tests/test_it_translation.py, tests/test_pt_etymology.py, tests/test_pt_example.py, tests/test_pt_form.py, tests/test_pt_gloss.py, tests/test_pt_head_line.py, tests/test_pt_linkage.py, tests/test_pt_sound.py, tests/test_pt_translation.py, tests/test_th_desc.py, tests/test_th_example.py, tests/test_th_gloss.py, tests/test_th_linkage.py, tests/test_th_translation.py
And clean up test temp files in it, pt, th editions.
=> [th] extract "lo-alt" form template and notes section

src/wiktextract/thesaurus.py, src/wiktextract/wiktionary.py
main process won't hang if one of worker process is crashed or killed
I only compared zh and th editions, just one minute less.
=> Use `concurrent.futures.ProcessPoolExecutor`

src/wiktextract/extractor/en/inflection.py, src/wiktextract/extractor/en/linkages.py
Also commented out two error message that were spamming a bit.
=> [en] Fix exception, dict is not pydantic object

src/wiktextract/extractor/en/page.py
=> [en] Also handle `Template:trans-top-see`

src/wiktextract/data/th/config.json
used in "มอดูล:glossary/data" Lua module
=> [th] add "ภาคผนวก:อภิธานศัพท์" appendix page

src/wiktextract/extractor/tr/inflection.py, src/wiktextract/extractor/tr/page.py, src/wiktextract/extractor/tr/section_titles.py, src/wiktextract/extractor/tr/tags.py, src/wiktextract/extractor/tr/translation.py, tests/test_tr_inflection.py, tests/test_tr_translation.py
Strange table headers, don't know what they mean.
=> [tr] extract "tr-ad-tablo" and "tr-eylem-tablo" table templates

src/wiktextract/extractor/el/page.py, src/wiktextract/extractor/el/pos.py, tests/test_el_glosses.py
=> [el] Continuation from #1094 in a separate PR because I don't want to mess stuff up in git; "bl"-template handling

src/wiktextract/extractor/ru/inflection.py, src/wiktextract/extractor/ru/page.py
=> [ru] extract "мест ru *" and "числ ru *" table templates

src/wiktextract/extractor/ru/page.py
=> [ru] extract "прил-ru" and "сущ-ru" forms table templates

src/wiktextract/extractor/ru/inflection.py, src/wiktextract/extractor/ru/page.py, src/wiktextract/extractor/ru/section_titles.py, src/wiktextract/extractor/ru/tags.py
=> [ru] improve extract POS type code

src/wiktextract/extractor/ru/inflection.py, src/wiktextract/extractor/ru/models.py, src/wiktextract/extractor/ru/page.py, tests/test_ru_gloss.py
=> [ru] fixes for forms table templates

src/wiktextract/extractor/de/gloss.py, src/wiktextract/extractor/de/utils.py, tests/test_de_etymology.py, tests/test_de_gloss.py
and add file "test_de_etymology.py" I forgot to stage in last pr
=> [de] fix empty gloss string check JSON errors

src/wiktextract/extractor/es/pos.py, tests/test_es_forms.py
=> [es] extract new "es.sust", "es.adj", "es.v" POS header templates

src/wiktextract/data/ms/config.json
page "Lampiran:Glosari" is used in "Modul:glossary/data"
=> [ms] add appendix pages, fix index nil Lua errors

src/wiktextract/data/overrides/en.json
fix #1163, remove this when 20250520 dump file released
=> [en] override page "Template:lookfrom"

src/wiktextract/extractor/en/linkages.py
=> [en] decode tags in alternative forms templates

src/wiktextract/extractor/en/page.py
=> [en] add another word's thesaurus data for "syn" template

src/wiktextract/extractor/en/pronunciation.py
=> [en] fix `IndexError` exception

src/wiktextract/extractor/ru/gloss.py
=> [ru] don't extract "помета" template as gloss if has "nocolor" arg

tests/test_el_glosses.py
Simple test following the discussion at #1185
=> [el] Test ":" list with a single item

src/wiktextract/data/overrides/zh.json, src/wiktextract/extractor/zh/page.py
=> [zh] fixes for low quality pages

src/wiktextract/extractor/de/inflection.py, tests/test_de_forms.py
=> [de] extract pronoun forms table

src/wiktextract/extractor/de/inflection.py, src/wiktextract/extractor/de/page.py
=> [de] extract form table in page "beide"

src/wiktextract/extractor/es/conjugation.py, tests/test_es_conj.py
=> [es] translate pronoun tags

src/wiktextract/extractor/es/conjugation.py
TypeError: cannot unpack non-iterable NoneType object
=> [es] fix "TypeError" exception

src/wiktextract/extractor/ku/tags.py
https://github.com/tatuylonen/wiktextract/commit/5c65a9dc11b86f3170cd72d1c8390b6c92b78715#r159518954
=> [ku] correct tag translation

src/wiktextract/extractor/pt/linkage.py, src/wiktextract/extractor/pt/models.py, src/wiktextract/extractor/pt/page.py, src/wiktextract/extractor/pt/pronunciation.py, src/wiktextract/extractor/pt/section_titles.py, src/wiktextract/extractor/pt/tags.py, tests/test_pt_sound.py
=> [pt] extract zh pronunciation section

src/wiktextract/extractor/en/page.py
example page "outer space", "twit", "emancipate"
=> [en] don't extract "sense" and "color panel" templates as example

src/wiktextract/extractor/ru/example.py, src/wiktextract/extractor/ru/gloss.py, tests/test_ru_gloss.py
=> [ru] don't add expanded category link to `gloss_nodes`

src/wiktextract/extractor/tr/pos.py
another crazy deep recursion template
=> [tr] add "tr-ünlü-çekimi" to `FORM_OF_TEMPLATES`

src/wiktextract/extractor/en/pronunciation.py, tests/test_en_pronunciation.py
modified from th edition code, fix #1288
=> [en] extract "th-pron" template

src/wiktextract/extractor/en/pronunciation.py, src/wiktextract/extractor/en/zh_pron_tags.py, src/wiktextract/extractor/zh/pronunciation.py, src/wiktextract/extractor/zh/tags.py, src/wiktextract/tags.py, tests/test_zh_pronunciation.py
this Pinyin phonetic data uses a different HTML layout than Puxian Min pronunciation data in page "經理"
=> [en, zh] extract phonetic pinyin in zh-pron template

src/wiktextract/extractor/zh/linkage.py, src/wiktextract/extractor/zh/tags.py, tests/test_zh_linkage.py
and don't combine same words in the table
=> [zh] extract note tags in "zh-dial" template

src/wiktextract/extractor/en/inflectiondata.py
=> [en] Add table header "genitive-dative" for Romanian

src/wiktextract/extractor/zh/models.py, src/wiktextract/extractor/zh/page.py, src/wiktextract/extractor/zh/pronunciation.py, src/wiktextract/extractor/zh/tags.py, tests/test_zh_inflection.py
Simplified Chinese alternative forms and anagrams are only available in expanded nodes
=> [zh] expand "zh-forms" template

src/wiktextract/extractor/en/page.py, src/wiktextract/extractor/en/type_utils.py, src/wiktextract/extractor/zh/page.py, tests/test_en_page.py, tests/test_zh_inflection.py
modified from zh edition code 48872cc
=> [en] expand "zh-forms" template

src/wiktextract/extractor/fr/gloss.py, src/wiktextract/extractor/it/pos.py, src/wiktextract/extractor/ja/pos.py, src/wiktextract/extractor/ms/pos.py, src/wiktextract/extractor/pt/pos.py, tests/test_fr_gloss.py, tests/test_it_gloss.py, tests/test_ja_gloss.py, tests/test_ms_gloss.py, tests/test_pt_gloss.py
Previous code only add the tag to `WordEntry`.
=> [fr, ja, pt, it, ms] add "form-of" tag to `Sense`

src/wiktextract/extractor/en/descendant.py, src/wiktextract/extractor/zh/descendant.py, tests/test_en_descendant.py
=> [en, zh] add tag in "desc" template to the correct instance

src/wiktextract/extractor/fr/inflection.py, src/wiktextract/extractor/fr/tags.py, tests/test_fr_inflection.py
`extract_fr_verbe_flexion()` could be deleted when the template is edited on Wiktionary to use the correct table header wikitext
=> [fr] combine some inflection table template functions

src/wiktextract/extractor/fr/conjugation.py
Annexe:Déclinaison_en_allemand/angemessen
=> [fr] extract "Onglets conjugaison" template in declension pages

src/wiktextract/extractor/fr/inflection.py, src/wiktextract/extractor/fr/tags.py, tests/test_fr_inflection.py
fix a typo that disable the test of this template
=> [fr] extract "avk-tab-conjug" table template
