tatuylonen/wiktextract

wiktwords

Exit with an error message if the user tries to set `--num-threads`
on a system where it leads to program errors. Killing the program
early with a helpful message is much preferable to the crash with
stack traces emitted several minutes into processing (at the
beginning of phase 2).
Fixes #151.

avoid crashes with illegal --num-threads option

---

wiktextract/wiktionary.py
wiktwords

I'm trying to parse the Spanish dump file and find the command takes a long time parsing [Wikcionario:Frecuencias/Finés](https://es.wiktionary.org/wiki/Wikcionario:Frecuencias/Fin%C3%A9s/000001-010000) pages. These pages are not word pages and this pull request ignores them so the command won't waste over ten hours parsing them.

Ignore Spanish Wiktionary Wikcionario pages

---

get_languages.py
wiktextract/config.py
wiktextract/data/zh/languages.json
wiktextract/page.py

All titles are changed to lower case in the `other_subtitles.json` file in the previous commit.
I also add simplified language names for the Chinese Wiktionary.

Use the lower case title in `fix_subtitle_hierarchy()`

---

tests/test_infl_map_control_flow.py
tests/test_inflection_table_context.py
wiktextract/inflection.py
wiktextract/inflectiondata.py
wiktextract/page.py
wiktextract/tags.py

Implemented here:
* page/parse_inflection now splits the to-be-parsed text into sections with one top-level template each
* including text after the template (and for the first template, text before it)
* this enables us to pass down the name of those templates (if any) using a TableContext object to the parsing routines
* added new field into output-json alongside the `table-tags`-tagged form field called `inflection-template` with the name
* added a new infl_map condition called `inflection-template` which evaluates as true when TableContext.template_name is in or equal to its value
This allows us to more easily debug issues with templates (less hunting down) and to finally have infl_map rules that handle single top-level templates without disturbing anything else. This is a weapon of …

Top-level template name parsing as usable data

---

wiktextract/data/zh/linkage_subtitles.json
wiktextract/data/zh/pos_subtitles.json
wiktextract/page.py

This pull request adds some missing POS and linkage heading texts for Chinese Wiktionary and pre-expands POS heading templates whose names start with "=" like [=n=](https://zh.wiktionary.org/wiki/Template:=n=).

Pre-expand Chinese Wiktionary POS template and add more POS heading text

---

.gitignore
README.md
requirements.txt

I was able to run tests via VS Code on Windows following these instructions. 
There is only one error, related to bz2 decompression, no `/bin/sh`, but that's a known problem on Windows, I'll try to fix it next, so that all tests can pass.

Add Windows VS Code instructions

---

get_languages.py
wiktextract/data/cs/languages.json
wiktextract/data/sk/languages.json

This commit adds code to generate languages.json for Czech and Slovak. I haven't run Wiktextract on these languages yet, but maybe the code is already useful to others who want to work on other Wiktionaries because it shows how to parse the source code instead of expanding the templates (because sometimes you can't expand them as there is no function to invoke).

Add languages.json for Czech and Slovak

---

get_languages.py
wiktextract/data/en/languages.json

Wikimedia projects use some nonexistent/retired ISO 639 language codes. Fixes #217.

Add Wikimedia language codes to `data/en/languages.json`

---

wiktextract/form_descriptions.py

Noticed some spurious romanizations. Consider for example [Reconstruction:Latin/sufferio](https://en.wiktionary.org/wiki/Reconstruction:Latin/sufferio).  `parse_word_head()` was going through the cleaned version of `{{la-verb|4|*sufferiō|*sufferīv|*suffert}} {{lb|la|Proto-Romance}}`, which is `*sufferiō (present infinitive *sufferīre, perfect active *sufferīvī, supine *suffertum); fourth conjugation (Proto-Romance)`, and was determining `Proto-Romance` to be a romanization. This can be ruled out as a romanization since `{{lb}}` generates the category `Proto-Romance`, which is in `data["categories"]`. So this PR adds a check to make sure cases like this are avoided. 
Now, the spurious romanization is gone, but there now is a `DEBUG: unrecognized head form: Proto-Romance` that gets logged …

don't classify desc as romanization if it is in data["categories"]

---

wiktextract/tags.py

See #233. 
A general speculation:
The cases in this PR all result from head lines like: `{{some-head-template|args...}} {{tlb|args...}}` or `{{some-head-template|args...}} {{lb|args...}}`, where the `{{tlb}}`/`{{lb}}` expansion adds something in parentheses that gets misinterpreted as a romanization (e.g. `*kesä (Finno-Permic)`). I feel like it should be possible to put something more robust in place to deal with this general case by looking at the [language-specific data](https://en.wiktionary.org/wiki/Special:PrefixIndex/Module:labels/data/lang/) in [`Module:labels/data`](https://en.wiktionary.org/wiki/Module:labels/data) and disallowing every possible label in the current language. For example [`Module:labels/data/lang/qwm`](https://en.wiktionary.org/wiki/Module:labels/data/lang/qwm) …

add to uppercase_tags to avoid spurious romanizations

---

wiktextract/tags.py

If I understood correctly the comment in #233, then these should also go here, as they are analogous to dialects.

add Proto-Georgian-Zan/Proto-Kartvelian uppercase_tags

---

usertools/language_data.py

Outputs two JSON files.
A languages file with entries like:
```json
"en": {
"aliases": [
"Modern English",
"New English"
],
"ancestors": [
"ine-pro",
"gem-pro",
"gmw-pro",
"ang",
"enm"
],
"canonicalName": "English",
"code": "en",
"family": "gmw",
"kind": "regular",
"nonEtymologyOnly": "en",
"otherNames": [],
"parents": [
"enm"
],
"scripts": [
"Latn",
"Brai",
"Shaw",
"Dsrt"
],
"varieties": [
"Polari",
"Yinglish"
],
"wikidataItem": "Q1860",
"wikipediaArticle": "English language"
},
```
A families file with entries like:
```json
"gmw": {
"canonicalName": "West Germanic",
"code": "gmw",
"otherNames": [],
"protoLanguage": "gmw-pro",
"superfamilies": [
"ine",
"gem"
],
"wikidataItem": "Q26721",
"wikipediaArticle": "West Germanic languages"
},
```

Usertools script to get detailed languages and families data from enwiktionary dump

---

usertools/sqlite_dictionary.py

I think for a lot of applications it is useful to have the data as an SQLite file, mostly because it allows searching for words in 1 - 2 milliseconds and to filter things like languages. This script generates the columns automatically so there shouldn't be a lot of maintenance burden. It also demonstrates how to get a proper collation because by default SQLite is pretty weak there and doesn't even support case insensitive search for cyrillic, for example. (And because I found it to be a somewhat confusing topic.)
Additionally I added a way to not only search the words but also the inflections for words (both diacritic/case insensitive). It seems to work with the entire dump. From the 15 GB dump you get a 23 GB database (due to indexing).

Loading the dump into a SQLite DB

---

wiktextract/wiktionary.py
wiktextract/wiktwords.py

These two functions won't be called if dump file path is not passed to the wiktwords command.
Requires https://github.com/tatuylonen/wikitextprocessor/pull/53

Overwrite pages and analyze templates when using `--page`

---

wiktextract/clean.py
wiktextract/config.py
wiktextract/extractor/en/page.py
wiktextract/extractor/en/thesaurus.py
wiktextract/extractor/share.py
wiktextract/extractor/zh/page.py
wiktextract/page.py

I have tested a few Chinese Wiktionary pages([大家](https://zh.wiktionary.org/zh/大家), [manga](https://zh.wiktionary.org/wiki/manga), [癸卯](https://zh.wiktionary.org/wiki/癸卯)), and the code can extract etymology, gloss, example and pronunciation data.
Changes:
- I changed the "english" key to "translation" in the "examples" dictionary for `zh/page.py` extractor, but didn't change the code in `en/page.py` file.
- and use a spacial page link to create the ogg file link
For future works:
- categories data aren't created in this pull request
- sense tags aren't translated, that could be done by extracting translation data from https://zh.wiktionary.org/wiki/Module:Labels/data.
- `extract_examples()`, `extract_pronunciation()` could be moved to separate files if they grow longer

Add Chinese Wiktionary extractor

---

wiktextract/extractor/zh/page.py
wiktextract/extractor/zh/pronunciation.py

- Fix the raw regex string and warning function in my previous pull request.
- Set example type to `quote` for zh-x template.
- And some changes to the pronunciation extractor code.
The `create_audio_url_dict()` could be shared by other language extractors later.

A few changes to the Chinese Wiktionary extractor

---

languages/get_data.py
usertools/language_data.py

The zh.lua file needs update because the `Module:Languages/alldata` page got deleted from Chinese Wiktionary. But the languages JSON file can also be updated via the MediaWiki API(`get_data_remote.py`), which should still work.

Update scripts for processing language data

---

languages/get_data.py
usertools/language_data.py
wiktextract/extractor/zh/linkage.py
wiktextract/extractor/zh/page.py
wiktextract/extractor/zh/thesaurus.py
wiktextract/page.py
wiktextract/thesaurus.py

I use the [rapidfuzz](https://github.com/maxbachmann/RapidFuzz) package(it's the dependency of package `levenshtein`) to find gloss string that similar to the linkage term's sense string. I tried to find how the English extractor does this but couldn't find it.
And I search the thesaurus database instead of parse the expanded tree of [`zh-syn-saurus`](https://zh.wiktionary.org/wiki/Template:Zh-syn-saurus) template because this template and other `*-saurus` templates use the same wikitext from thesaurus pages so it doesn't need to be parsed again.

Extract linkage data for Chinese Wiktionary

---

languages/lua/zh.lua
wiktextract/data/en/languages.json
wiktextract/data/zh/languages.json

Thanks to the heads up from #271, this fixes the lua code for getting Chinese wiktionary language data; the modules were apparently significantly revised recently. Updates use `zhwiktionary-20230620-pages-articles.xml.bz2` and `enwiktionary-20230620-pages-articles.xml.bz2`.

update Chinese and English language data

---

tests/test_zh_headword.py
wiktextract/config.py
wiktextract/datautils.py
wiktextract/extractor/zh/example.py
wiktextract/extractor/zh/headword_line.py
wiktextract/extractor/zh/page.py

`assert` are removed from `data_append()` and `data_extend()` because `Mock` objects won't pass `assert isinstance`.

Extract form and gender data from Chinese Wiktionary headword line

---

tests/test_zh_example.py
tests/test_zh_gloss.py
tests/test_zh_headword.py
wiktextract/extractor/share.py
wiktextract/extractor/zh/example.py
wiktextract/extractor/zh/headword_line.py
wiktextract/extractor/zh/page.py

Check HTML tag and class name to find form text, gender text and romanization text, this is more reliable then only process the expanded plain text.
The mock HTML return value in tests are written in a single line because I tried to format them but `ikitextprocessor.Wtp.parse()` adds some extra `preformated` nodes.

Prase expanded headword line HTML tags

---

wiktextract/extractor/en/page.py
wiktextract/extractor/ruby.py
wiktextract/extractor/zh/headword_line.py
wiktextract/extractor/zh/page.py
wiktextract/extractor/zh/thesaurus.py

- Extract Japanese ruby tag code are moved to a new file for sharing with different extractors.
- Extract Furigana data from headword line and gloss text for Chinese Wiktionary.

Extract Japanese Furigana data in Chinese Wiktionary

---

pyproject.toml

Set `tool.setuptools.packages` won't include subpackages. The correct fix is to using the
"src-layout"(https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout). Otherwise we'll have to add path to the `exclude` list when a new directory is created.

Fix `wiktextract.extractor` not found error when install from source

---

wiktextract/extractor/en/page.py

This warning log should be added in commit https://github.com/tatuylonen/wiktextract/commit/246322ec95accb68e976d80cf8f9245a487638dc

Add a warning when an example template is misused in gloss text

---

wiktextract/extractor/zh/example.py
wiktextract/page.py

Language category texts in Chinese Wiktionary don't have white space after the first language word, so I make the `[ /]` pattern optional. Otherwise the categories from the last word won't be removed from all previous data(they are also added from the same `process_categories()` function).

Extract `ux` and `uxi` Chinese Wiktionary templates and remove different language categories

---

wiktextract/clean.py
wiktextract/data/fr/languages.json
wiktextract/data/fr/other_subtitles.json
wiktextract/data/fr/pos_subtitles.json
wiktextract/datautils.py
wiktextract/extractor/fr/gloss.py
wiktextract/extractor/fr/page.py
wiktextract/extractor/zh/page.py
wiktextract/page.py

The code in `fr/page.py` are mostly copied from `zh/page.py` and it only extract the raw etymology and gloss text.

Add French WIktionary extractor code

---

tests/test_zh_headword.py
wiktextract/extractor/en/page.py
wiktextract/extractor/en/thesaurus.py
wiktextract/extractor/fr/inflection.py
wiktextract/extractor/fr/page.py
wiktextract/extractor/ruby.py
wiktextract/extractor/share.py
wiktextract/extractor/zh/example.py
wiktextract/extractor/zh/gloss.py
wiktextract/extractor/zh/headword_line.py
wiktextract/extractor/zh/inflection.py
wiktextract/extractor/zh/linkage.py
wiktextract/extractor/zh/page.py
wiktextract/extractor/zh/pronunciation.py
wiktextract/extractor/zh/thesaurus.py
wiktextract/extractor/zh/translation.py
wiktextract/inflection.py
wiktextract/page.py
wiktextract/pronunciations.py

This implements the changes in https://github.com/tatuylonen/wikitextprocessor/pull/87
Basically, I got really annoyed with type-checking WikiNode.args, because .args can be either a string OR a list of lists containing argument stuff... This also makes it more readable, hopefully.

Apply WikiNode.args -> .sarg/.largs in Wikitextprocessor

---

.github/workflows/test.yml

Deploy to GitHub Pages action failed, maybe update `actions/upload-pages-artifact` could fix it.

Update GitHub Actions dependencies

---

tests/test_fr_form_line.py
tests/test_fr_gloss.py
wiktextract/extractor/fr/form_line.py

Chinese word might use a single "zh-mot" template in form line

Process French Wiktionary "zh-mot*" templates in form line

---

tests/test_fr_form_line.py
wiktextract/extractor/fr/form_line.py

IPA location tags usually expand to `(location)` and is after a "pron" template.

Add French Wiktionary IPA location template as sound tag

---

tests/test_fr_pronunciation.py
tests/test_fr_translation.py
wiktextract/extractor/fr/page.py
wiktextract/extractor/fr/translation.py

Tested with page https://fr.wiktionary.org/wiki/bonjour Only the "Amazighe standard marocain" language's translation text got removed by `clean_node()`.

Extract French Wiktionary translation list

---

.github/workflows/test.yml

The 20M "taxondata.py" file creates a ridiculous 143M coverage HTML file, which makes the deploy action failed after the default 10m timeout.

Fix deploy page action timeout error

---

tests/test_fr_etymology.py
wiktextract/extractor/fr/page.py

This template is used for words that don't have etymology data.

Don't expand "ébauche-étym" template to etymology text

---

tests/test_fr_page.py
wiktextract/extractor/fr/page.py

While exploring the progress to the French extractor you've made recently (well, done already!), I wanted to run the script from the default entry point via `wiktwords.py` but quickly discovered that there are still problems in `fr/page.py`.
One I fixed already: 
- https://github.com/tatuylonen/wiktextract/commit/fd53cdd1dfc5b3fc2a84595ab23cb113525ca1d5: Originally, empty dicts were created  instead of empty sets.
The main problem: 
- In several places, the code makes use of the inexistent instance method `find_content` on objects of the `WikiNode` class, for example in https://github.com/tatuylonen/wiktextract/blob/05321e53017a175dd2c7a293e1b4f784764a81f7/wiktextract/extractor/fr/page.py#L217 This seems intentional but I'am unsure what to do about it. @xxyzz Does this rely on some not …

Fix 'parse_page' for French extractor

---

tests/test_fr_etymology.py
tests/test_fr_gloss.py
tests/test_fr_page.py
wiktextract/datautils.py
wiktextract/extractor/fr/etymology.py
wiktextract/extractor/fr/gloss.py
wiktextract/extractor/fr/inflection.py
wiktextract/extractor/fr/page.py

This pull request extracts French Wiktionary etymology list and breaks the list text to JSON list "etymology_texts"(this is a str type for English JSON file), examples can be found in test cases.

Extract French Wiktionary etymology list

---

tests/test_fr_linkage.py
wiktextract/extractor/fr/form_line.py
wiktextract/extractor/fr/linkage.py

Combine separated synonyms tag string and template

---

wiktextract/extractor/fr/gloss.py

Page https://fr.wiktionary.org/wiki/topo_del_Mediterraneo_occidentale uses an empty "exemple" template: "{{exemple|lang=it}}"

Ignore empty French Wiktionary "exemple" template

---

tests/test_fr_inflection.py
wiktextract/extractor/fr/inflection.py

This table has two rwo headers and the first header is extended to two rows with the "rowspan" attibute.

Extract inflection table expanded from "fr-accord-personne" template

---

.github/workflows/test.yml
tests/test_de_page.py
wiktextract/extractor/de/gloss.py
wiktextract/extractor/de/page.py
wiktextract/extractor/fr/page.py
wiktextract/extractor/zh/headword_line.py
wiktextract/extractor/zh/page.py

Only the level two language title node is used in these functions, other nodes are ignored and the code could be simplified with the `WikiNode.find_child()` method.

Simplify `parse_page()` in extractor code

---

json_schema/fr.json
json_schema/validate.py
json_schema/zh.json
pyproject.toml
tests/test_fr_gloss.py
tests/test_zh_example.py
wiktextract/extractor/fr/gloss.py
wiktextract/extractor/zh/example.py

I'm run the validation code but it is not finish yet, the schema might not match the JSON file.

Add French and Chinese Wiktionary JSON schema

---

tests/test_fr_inflection.py
wiktextract/extractor/fr/inflection.py

Example page: https://fr.wiktionary.org/wiki/fenil#Nom_commun_4
Template: https://fr.wiktionary.org/wiki/Modèle:ro-nom-tab

Extract inflection table that has column with `colspan` attr

---

src/wiktextract/clean.py

This pr fixes all alerts in GitHub Code Scanning exception one alert of this regex pattern: https://github.com/tatuylonen/wiktextract/blob/08407b3a8031ec31482f2b457789e0896768ad07/src/wiktextract/clean.py#L1446
I don't know how to fix that pattern...

Fix regex alerts

---

languages/get_data.py
src/wiktextract/clean.py
src/wiktextract/config.py
src/wiktextract/data/fr/config.json
src/wiktextract/extractor/fr/gloss.py
src/wiktextract/extractor/fr/inflection.py
src/wiktextract/extractor/fr/page.py
src/wiktextract/extractor/fr/translation.py
src/wiktextract/form_descriptions.py
src/wiktextract/inflection.py
src/wiktextract/page.py
src/wiktextract/pronunciations.py
src/wiktextract/wiktionary.py
src/wiktextract/wiktwords.py
src/wiktextract/wxr_context.py
tests/test_clean.py
tests/test_fr_etymology.py
tests/test_fr_form_line.py
tests/test_fr_gloss.py
tests/test_fr_inflection.py
tests/test_fr_linkage.py
tests/test_fr_page.py
tests/test_fr_pronunciation.py
tests/test_fr_translation.py

Requires changes in https://github.com/tatuylonen/wikitextprocessor/pull/122
This pr adds a new configure JSON file for each Wiktionary edition extractor to disable `Wtp.analyze_templates()` and disk extracting thesaurus pages.

Disable analyze templates and extract thesaurus pages features for French Wiktionary

---

src/wiktextract/extractor/fr/linkage.py
src/wiktextract/extractor/fr/page.py
src/wiktextract/extractor/share.py
tests/test_fr_linkage.py

If the sublist node is not filtered, the child list node will be added to the parent node's tag.

Exclude sublist child node from linkage list item node

---

src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/fr/page.py
tests/test_de_page.py

Currently the German and French extractors don't make use of the "capture_language_codes" configuration and capture all languages by default.
This commit adds support for this feature.

Add support for "capture_language_codes" in de and fr extractors

---

src/wiktextract/wiktwords.py

Fix missing skip_analyze_templates argument in wiktwords.py

---

src/wiktextract/extractor/de/example.py
src/wiktextract/extractor/de/gloss.py
src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/de/translation.py
src/wiktextract/extractor/de/utils.py
tests/test_de_example.py
tests/test_de_gloss.py
tests/test_de_page.py
tests/test_de_pronunciation.py
tests/test_de_translation.py

I have covered the default cases of the translation tables in the German Wiktionary. It should extract >95% (probably more) of the usable information.
Notably there are three rare types of data/formats that I don't want to cover at the moment:
- Translation links to another page (ca. 1.1% of pages)
- Dialect information (ca. 0.12% of pages)
- Non-standard senseid formats (currently extracted but not sense-disambiguated) (ca. 0.03% of pages) 
The percentages come from the sample of ~18000 pages that I test on during development. I left comments and dummy code in the files to keep track of this and suggest an entry point for future implementation. 
---
As a bonus, I now configured the isort extension in my IDE and reordered the imports in the German extractor files.

Extract translations from German Wiktionary 

---

src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/de/semantic_relations.py
src/wiktextract/extractor/de/translation.py
src/wiktextract/extractor/de/utils.py
tests/test_de_semantic_relations.py
tests/test_de_utils.py

This adds support for extracting different several kinds of semantic relations from the German Wiktionary. It covers the most prevalent way in which these sections are structured.
It does not:
- extract modifiers (tags) to a semantic relation, e.g.: in `{{Synonyme}}\n:[1] [[Kokosnusspalme]], ''wissenschaftlich:'' [[Cocos nucifera]]` from [Kokospalme](https://de.wiktionary.org/wiki/Kokospalme) the tag `wissenschaftlich` will be ignored
- extract semantic relations structured using sublists, e.g. Wortbildungen in [Byte](https://de.wiktionary.org/wiki/Byte)
- extract semantic relations formated other than via a wiki link, e.g. in `{{Redewendungen}}:[1] ''[[aller Anfang ist schwer]].` from [aller](https://de.wiktionary.org/wiki/aller) the relation will not be captured since generally italics …

Extract semantic relations from German Wiktionary.

---

json_schema/fr.json
json_schema/zh.json

I noticed that the current schemas state that the language codes are ISO 639-1. But there are many codes that are not ISO 639-1. There are many ISO 639-3 codes. Also, there are many non-ISO codes that are used by conventions that depend on the specific language edition. For example, proto-languages in zh and en have codes like `afa-pro`, while in fr they have codes like `proto-afro-asiatique` -- but neither of these code types corresponds to ISO codes.

adjust json schema descriptions for language code

---

src/wiktextract/extractor/fr/inflection.py
tests/test_fr_inflection.py

and filter table row nodes that have "invisible" class

Ignore "Commun" header cell in the French Wiktionary "sv-nom-c-ar" template

---

src/wiktextract/wiktwords.py

`analyze_and_overwrite_pages()`'s last parameter is `skip_analyze_templates`

---

languages/get_data_de.py
languages/get_data_es.py
src/wiktextract/data/es/config.json
src/wiktextract/data/es/languages.json
src/wiktextract/extractor/de/translation.py

The Spanish Wiktionary doesn't use module data to define language codes. So I had to look for other sources of language data.
Fortunately, there seems to be a comprehensive, automatically-generated list of language codes with their corresponding Spanish names in the Appendix: [Apéndice:Códigos de idioma](https://es.wiktionary.org/wiki/Ap%C3%A9ndice:C%C3%B3digos_de_idioma)
There is probably a better way of organizing the get_data logic for different languages than by just adding another script file. But for more or less a one-time thing, this should suffice.

Add languages.json for Spanish Wiktionary

---

src/wiktextract/extractor/zh/translation.py

Check if the first template paramter of `trans-top` exists.

Fix None type WikiNode error in Chinese translation extractor

---

.github/workflows/container.yml
Containerfile
README.md

Run code in a container could solve all the environment errors. We could publish the container image to [GitHub Packages](https://github.com/tatuylonen/wiktextract/packages) so the users don't need to build the image. This could also relief the burden of compatible with older Python verisons.

Add Containerfile

---

.github/workflows/container.yml

this could be used to update the wikitextprocessor package in the image

Make publish container image action manually triggerable

---

src/wiktextract/config.py
src/wiktextract/datautils.py
src/wiktextract/extractor/en/page.py
src/wiktextract/form_descriptions.py
src/wiktextract/inflection.py
src/wiktextract/linkages.py
src/wiktextract/page.py
src/wiktextract/pronunciations.py
src/wiktextract/translations.py

Attibutes are used in pydantic models. An `assert` is removed because pydanic could be passed but we don't want to import pydantic for code doesn't use it.
And the `wxr` argument should be removed from `data_append()` and `data_extend()`.
For #392

Check data attibute in `data_append()` and `clean_node()`

---

Makefile
src/wiktextract/extractor/en/page.py

Commit f0d0195e5833e828530fcbb1854804803c6701e7 in wikitextprocessor should fix this issue with newlines 'missing' at the start of {{multitrans}} templates.
What was the issue, it turns out, that those phantom newlines that I thought was something more nebulous was simply... Missing newlines! In wikitext, when expanding a template (or parser function), if the result text has a special character (*;:# or "{|") at the start of the string, it inserts a newline before the string.
This wasn't very well documented and Tatu missed it.

Remove "multitrans" kludge with newlines

---

src/wiktextract/extractor/en/page.py
tests/test_head.py

This bug was introduced from pr #393, fixes #405.

Use language codes in `HEAD_TAG_RE` pattern

---

json_schema/es.json
src/wiktextract/extractor/es/models.py
src/wiktextract/extractor/es/page.py
src/wiktextract/extractor/es/pronunciation.py
tests/test_es_gloss.py
tests/test_es_pronunciation.py

This is basically to parse the [`{pron-graf}`](https://es.wiktionary.org/wiki/Plantilla:pron-graf) template and extract pronunciation data. The template itself is very vast and covers also different spellings.
I am not 100% whether extracting spelling data to a separate `spelling` field is the best way to proceed. But it's a start.

Extract pronunciation from Spanish Wiktionary

---

src/wiktextract/extractor/fr/linkage.py
src/wiktextract/extractor/fr/page.py

page "ferme eut’bouque tin nez i va queire éd’dins". The `phrases` argument is for linkage lists but is used as POS in this page.

Fix index out of range error in French Wiktionary

---

src/wiktextract/pronunciations.py

Fixes an issue where the index of `audios` was out of range because we emptied it in an earlier iteration of the loop. (Line 566 with the IPA audio file stuff, `audios` is emptied on line 639).
This was my fault from last year, for some reason this bit of the code that should be handled just once was put inside a large for loop, and some kind of brainfart must have made me think that "this should run only once, let's prevent the if-block from happening by emptying `audios` after we've done the processing"... And I didn't think that `audios` was accessed elsewhere in the loop, which triggered this pretty rare bug.
I'm putting this here overnight just in case I missed something obvious. But I'm pretty sure this is just my own mistake originally...

Move code out of for loop that didn't belong there

---

src/wiktextract/data/es/linkage_subtitles.json
src/wiktextract/data/es/other_subtitles.json
src/wiktextract/extractor/es/example.py
src/wiktextract/extractor/es/gloss.py
src/wiktextract/extractor/es/linkage.py
src/wiktextract/extractor/es/models.py
src/wiktextract/extractor/es/page.py
src/wiktextract/extractor/es/sense_data.py
tests/test_es_example.py
tests/test_es_page.py

This is primarily to extract examples from the Spanish Wiktionary.
Unfortunately, the data in the Spanish Wiktionary isn't ordered very hierarchically anymore within the POS sections. This is why the `page.py` became quite evolved, doing the heavy lifting to collect and group what belongs together.
Also unfortunately, the Spanish Wiktionary is not overly consistent in where to place information. Examples, for example, can be either placed within a template `{ejemplo|...}` (though additional information to that example is often placed outside the template) or in lists which may or may not use a marker `'''Ejemplo'''`. I believe I also saw some pages where examples would be in their own section `===Ejemplos===` but I am ignoring this for the moment as a rare case.
I did my best to document …

Extract examples from Spanish Wiktionary

---

json_schema/de.json
src/wiktextract/extractor/de/example.py
src/wiktextract/extractor/de/gloss.py
src/wiktextract/extractor/de/linkage.py
src/wiktextract/extractor/de/models.py
src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/de/translation.py
tests/test_de_example.py
tests/test_de_gloss.py
tests/test_de_linkages.py
tests/test_de_page.py
tests/test_de_pronunciation.py
tests/test_de_translation.py
tests/test_desc.py

This is to add pydantic classes to the German extractor.
In some cases, pydantic fields are defined as lists of strings where probably they could be just a string. I decided to accept for now this looser schema to avoid refactoring even more. This was already quite a bit more painful than I anticipated.

Add pydantic and json_schema to German extractor

---

json_schema/es.json
json_schema/ru.json
src/wiktextract/data/es/other_subtitles.json
src/wiktextract/extractor/de/linkage.py
src/wiktextract/extractor/de/utils.py
src/wiktextract/extractor/es/models.py
src/wiktextract/extractor/es/page.py
src/wiktextract/extractor/es/translation.py
src/wiktextract/extractor/ru/models.py
src/wiktextract/extractor/share.py
tests/test_es_translation.py
tests/test_share.py

Perhaps worth a discussion: I am reusing an utility that I wrote for the German Wiktionary: `split_senseids()`. This function currently is defined in `extractor/de/utils.py`. 
It would make sense to move it somewhere else since it's not  used exclusively by the German extractor anymore. Any suggestions?

Extract translations from Spanish Wiktionary

---

json_schema/ru.json
src/wiktextract/extractor/ru/models.py
src/wiktextract/extractor/ru/page.py
src/wiktextract/extractor/ru/pronunciation.py
tests/test_ru_pronunciation.py

More or less straightforward. I skipped some of the rarer pronunciation templates but indicated them in code with `# XXX:`
PS: I hope you don't mind the many simultaneous PRs. This is the last week where I can really focus on contributing to wiktextract, so I try to make the most of it.

Extract pronunciation from Russian Wiktionary

---

json_schema/es.json
src/wiktextract/data/es/linkage_subtitles.json
src/wiktextract/data/es/other_subtitles.json
src/wiktextract/extractor/es/linkage.py
src/wiktextract/extractor/es/models.py
src/wiktextract/extractor/es/page.py
src/wiktextract/extractor/es/sense_data.py
tests/test_es_linkage.py

This is as far as I planned to develop the Spanish extractor. 
Apart from places indicated with `# XXX: ...`, the biggest area of improvement would be perhaps to deal with form sections. In the Spanish Wiktionary, whenever a lemma can also be a conjugated/declinated form of a different word, this will be noted in a form section which are siblings to POS sections.
To get an order of magnitude, in the 20,000 pages I am developing on, I reach these form sections ca. 15,000 times. An example, for the word [pueblo](https://es.wiktionary.org/wiki/pueblo):
For me it's okay to not deal with these right now. But perhaps someone else will.

Extract linkages from Spanish Wiktionary

---

src/wiktextract/extractor/fr/models.py
src/wiktextract/extractor/zh/models.py

I forgot to use `forbid` in previous commits.

Forbid setting extra attributes during model initialization

---

src/wiktextract/page.py
tests/test_clean.py

Remove the bold wikitext causes error in English Wiktionary template "ja-usex". Bold and italic nodes are converted to plain text later somewhere in `clean_value()`.
Resolves tatuylonen/wikitextprocessor#170

Don't remove bold and italic wikitext before expanding nodes

---

src/wiktextract/extractor/fr/page.py
tests/test_fr_page.py

The code should append a new WordEntry object if the `pos` field is assigned in the last object of the `page_data` list.

Fix a bug that appends all senses to the same WordEntry object

---

src/wiktextract/extractor/fr/pronunciation.py
tests/test_fr_pronunciation.py

Other sections under "Prononciation" will also be processed now. Requires https://github.com/tatuylonen/wikitextprocessor/pull/173

Extract "Paronymes" section under the "Prononciation" section

---

src/wiktextract/extractor/en/page.py
tests/test_long.py
tests/test_page.py

Some pages use the template `zh-see` to redirect simplified Chinese characters don't have POS title. Not sure why the pr 174 of wikitextprocessor affects this test.
Another change is adding the redirect data to `pos_data` if it's not empty.

Remove pos length check in `test_long`

---

src/wiktextract/extractor/ru/linkage.py
src/wiktextract/extractor/ru/models.py
src/wiktextract/extractor/ru/pronunciation.py
tests/test_ru_pronunciation.py

This is in reply to #448 where @kristian-clausal mentions that the Russian extractor should use at least a basic Linkage model serializing to `{"word": linkage_word}`.
Mentioned in comment: https://github.com/tatuylonen/wiktextract/issues/448#issuecomment-1876986116_

Use linkage model in Russian Wiktionary

---

src/wiktextract/extractor/de/linkage.py
src/wiktextract/extractor/de/models.py
src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/de/translation.py
src/wiktextract/extractor/es/gloss.py
src/wiktextract/extractor/es/models.py
src/wiktextract/extractor/es/page.py
src/wiktextract/extractor/ru/models.py
src/wiktextract/extractor/ru/page.py
src/wiktextract/extractor/ru/translation.py
tests/test_de_example.py
tests/test_de_gloss.py
tests/test_de_linkages.py
tests/test_de_page.py
tests/test_de_pronunciation.py
tests/test_de_translation.py
tests/test_es_etymology.py
tests/test_es_gloss.py
tests/test_es_page.py
tests/test_es_pronunciation.py
tests/test_es_translation.py
tests/test_ru_gloss.py
tests/test_ru_page.py
tests/test_ru_pronunciation.py
tests/test_ru_translation.py

In response to #448 .
While I am fine with all the suggested changes, I still want to point out that `lang_name` is objectively the better property name than `lang`, thanks to being more descriptive and unique. 
However, for the sake of uniformity, I am fine with renaming it.

Align schemas of Spanish, Russian and German extractors

---

src/wiktextract/extractor/fr/conjugation.py
tests/test_fr_conj.py
tests/test_fr_form_line.py
tests/test_fr_gloss.py
tests/test_fr_inflection.py
tests/test_fr_linkage.py
tests/test_fr_note.py
tests/test_fr_translation.py

I only take a look the link parser code: https://github.com/tatuylonen/wikitextprocessor/blob/0cb88feb77be2e03ba0eac4aca1ea1cb4cba20f8/src/wikitextprocessor/core.py#L598
This seems not easy to fix.

Extract "Onglets conjugaison" template

---

src/wiktextract/extractor/fr/conjugation.py
tests/test_fr_conj.py

The `|-toi` table cell parse error was fixed in https://github.com/tatuylonen/wikitextprocessor/pull/182 thanks to @kristian-clausal.

Fix white spaces and empty cell in "Conjugaison:français/s’abattre"

---

src/wiktextract/extractor/zh/headword_line.py

Error page: https://zh.wiktionary.org/wiki/ރުޅި

Fix "index out of range" error in Chinese Wiktionary Maldivian pages

---

src/wiktextract/extractor/fr/translation.py
tests/test_fr_translation.py

All French translation data lacks language code is because the page doesn't use the "T" template, this commit should make all translation data has language code.
Issue #467

Get translation language code from "trad*" template parameter

---

src/wiktextract/extractor/de/models.py
src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/es/etymology.py
src/wiktextract/extractor/es/models.py
src/wiktextract/extractor/es/translation.py
tests/test_de_pronunciation.py
tests/test_es_etymology.py
tests/test_es_translation.py

Because I messed up my testing last time (by forgetting to use "--all" in wiktwords when generating the input json!!!!!), I need to do all the target language htmlgeneration attempts again, which will take a while but isn't complicated (now that I've figured out a procedure).

More other-edition field stuff

---

src/wiktextract/clean.py
src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/ruby.py
src/wiktextract/linkages.py
src/wiktextract/page.py
src/wiktextract/type_utils.py

Typing stuff, part two, this time so it's possible to rebase (memo to self: don't merge to update, rebase this branch as you go).
I already found a bug. Is there anything worse than looking at some code, seeing that it's wrong, and then finding out it was your own commit that did it?

 Typing stuff

---

src/wiktextract/wiktwords.py

This is why Python magic methods shouldn't be used, `not "False"` is `False`.

Fix bug introduced from 04ca7a8126e749f8fb500fdb96e43a8f8316d7ae

---

src/wiktextract/extractor/fr/inflection.py
tests/test_fr_inflection.py

Table cell node is used as header cell if it contains a bold node.

Process forms table expanded from "fr-verbe-flexion" template

---

src/wiktextract/extractor/fr/linkage.py
tests/test_fr_linkage.py

I should use `str.isdecimal()`, `str.isdigit()` returns `True` for letters that are not 0-9.

Fix `ValueError` in fr edition page "gigabit", "million", "亿"

---

src/wiktextract/extractor/ruby.py

Error page: https://zh.wiktionary.org/wiki/Egipt
Because error is triggered by a Lua error in the "desctree" template and the template wikitext is in the error message not for expansion so it seems inappropriate to add a test based on this page.

Add the missing `ns_prefixes` argument of `TemplateNode.__init__()`

---

src/wiktextract/extractor/de/linkage.py
src/wiktextract/extractor/de/models.py
src/wiktextract/extractor/de/translation.py
src/wiktextract/extractor/es/linkage.py
src/wiktextract/extractor/es/models.py
tests/test_de_linkages.py
tests/test_de_translation.py
tests/test_es_linkage.py

Sense ids in Wiktionary pages could be outdated or wrong, we shouldn't move the data extracted from other sections under the `Sense` field.
Fixes #478

Remove `Sense.translations` field from de edition's model

---

src/wiktextract/extractor/zh/section_titles.py
src/wiktextract/page.py

This error is caused by the wrong title wikitext, the linkage title should use the level 5 title, but a level 4 title(this is sense title) is used. Only one page has this error.

Fix `AssertionError` in zh edition page "Thesaurus:diatribe"

---

src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/de/pronunciation.py
tests/test_de_pronunciation.py

Some pages doesn't pass the IPA data to template "Lautschrift" and the `None` was added to the `ipa` field.

Fix 'str' object has no attribute 'extend' in de edition page "BU"

---

src/wiktextract/extractor/zh/descendant.py
src/wiktextract/extractor/zh/gloss.py
src/wiktextract/extractor/zh/headword_line.py
src/wiktextract/extractor/zh/inflection.py
src/wiktextract/extractor/zh/linkage.py
src/wiktextract/extractor/zh/models.py
src/wiktextract/extractor/zh/pronunciation.py
src/wiktextract/extractor/zh/section_titles.py
src/wiktextract/extractor/zh/thesaurus.py
src/wiktextract/extractor/zh/translation.py
tests/test_zh_descendant.py
tests/test_zh_gloss.py
tests/test_zh_headword.py
tests/test_zh_inflection.py
tests/test_zh_pronunciation.py
tests/test_zh_translation.py

Only tags used in en edition are added to the `tags` field.

Add `raw_tags` fields to zh edition pydantic models

---

src/wiktextract/wiktionary.py

- Fixes two undefined variables error.
- Check the `tags` field of the `item` variable, previous code check the `dt` variable which is the main dictionary data. And because en extractor doesn't have `tags` in the main dictionary, this error is not caught in test.

Fix `NameError` exception in `check_tags()`

---

src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/fr/tags.py
src/wiktextract/extractor/zh/models.py
src/wiktextract/extractor/zh/page.py
src/wiktextract/extractor/zh/section_titles.py
src/wiktextract/page.py
src/wiktextract/wiktionary.py
tests/test_page.py
tests/test_zh_descendant.py
tests/test_zh_gloss.py
tests/test_zh_headword.py
tests/test_zh_inflection.py
tests/test_zh_linkage.py
tests/test_zh_note.py
tests/test_zh_pronunciation.py
tests/test_zh_translation.py

Default is `unknown`, and `soft-redirect` for `zh-see` and `ja-see` templates.

Make zh edition's pydantic model `WordEntry.pos` field required

---

src/wiktextract/clean.py
src/wiktextract/form_descriptions.py
tests/test_clean.py

If an image is inline (it doesn't have any of a set of arguments that, like 'right' or 'thumb' etc.), then its `alt=` text should be printed when returned from clean_value.
To make it clearer that this is an `alt` text, and to make post-processing easier, we add `[Alt: ` + `]` around the text.

Inline images should print alt= text

---

src/wiktextract/page.py
tests/test_en_category.py

This huge regex pattern can't handle languages that have the same prefix("E" and "English"), split the category link by space and slash should serve the original code's purpose.
Fix #537

Remove category languages regex pattern

---

src/wiktextract/clean.py
tests/test_clean.py

also replace the hard-coded strings in `repl_link()`

Use `Wtp.namespace_prefixes()` to check if a link is an image

---

src/wiktextract/clean.py
tests/test_clean.py

I finally got this regex thing figured out. What
a nightmare.
Previously, if you had tables (`{| .. |}`) within
tables of wikitext, clean_value would not remove everything because it would do only one pass. We can't make this greedy, because then two separate tables would lead to the removal of everything between them too, so
negative lookahead is needed.
Do the usual "remove innermost table" thing until
no changes are detected, hope everything works out ok.
Q: Why do we remove tables, but not HTML `<table>...</table>` elements?
A: Good question! Because it's hard, and has been previously overlooked. A table will often just lead to garbled text when 'cleaned' from tags, etc. so it might be best to also remove all tables, and have the user handle them otherwise. XXX: remove HTML tables?

Handle tables inside tables in clean_value()

---

src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/share.py

Pages like "Casinospiel" put empty string parameter to "Audio" template.

Fix index out of range exceptions in de edition

---

src/wiktextract/datautils.py
src/wiktextract/extractor/en/page.py
src/wiktextract/linkages.py
tests/test_linkages.py

Previously we would just split on certain commas etc. even when a word or linkage contained them, creating extra partitions of words:
Hunde, die bellen, beißen nicht -> "Hunde", "die bellen", "beißen nicht".
This changes collects link data (visible link text strings where .alnum() == False) and passes it as a new parameter ultimately to split_on_comma_semi.
There, we use the links as part of the splitting regex, but ignore them when handling the iterations.
Also a couple of tests, but other tests fail.

Preliminary work on enabling not splitting links

---

src/wiktextract/extractor/en/page.py
tests/test_en_category.py

The code should only skip soft redirect templates, some templates like "C" could be used to extract category links. Issue #577

Don't skip all templates in en edition's `process_children()`

---

src/wiktextract/extractor/en/page.py
tests/test_page.py

English `Template:root` is a template that generates empty text in the etymology section, but contains useful argument data, so we want to save the template and handle the expansion text by marking it as coming from Template:root.
Sometimes etymology sections are just empty, so we need to check for that, too, and not add "etymology_text" fields to the data that are empty and annoy the manual validator written by Tatu.

En validation

---

src/wiktextract/form_descriptions.py
tests/test_head.py

I am really happy with this one. Minimal changes, after figuring out where the issue was.
The issue was: phrases and words with stuff like commas had their commas stripped away due to a general word-finding regex. The fix is to use a modified regex pattern if needed, when `links` data is provided.

Use link text data in word head detection regex

---

src/wiktextract/extractor/share.py
tests/test_utils.py

Some sound files use uppercase file extension

Fix 'OGG_url' not defined error in some zh edition pages

---

src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/section_titles.py

en edition templates "fi-stats-given-name" and "fi-stats-surname" put the end of wikitext link `]]` inside `#switch` parser function break our parser.
Error: https://kaikki.org/dictionary/All%20languages%20combined/errors/details-Invalid-source-given-for-fi-stats-surn-NnZNGQei.html
Template pages:
- https://en.wiktionary.org/wiki/Template:fi-stats-surname
- https://en.wiktionary.org/wiki/Template:fi-stats-given-name

Ignore "Statistics" sections to suppress "fi-stats-surname" Lua error

---

src/wiktextract/form_descriptions.py

Recently messed up some regex pattern generation things (didn't escape them), and I missed this one in the logs because the other exception was much more common.

Fix issue with malformed regex in parse_word_head

---

src/wiktextract/extractor/en/page.py

Turns out Template:root isn't the only template
in the etymology section that doesn't generate an expansion.

Generalize recognizing etymology templates without expansions

---

src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/thesaurus.py
src/wiktextract/extractor/es/page.py
src/wiktextract/extractor/fr/page.py
src/wiktextract/extractor/ru/page.py
src/wiktextract/extractor/zh/page.py
src/wiktextract/extractor/zh/thesaurus.py
src/wiktextract/logging.py
src/wiktextract/thesaurus.py
src/wiktextract/wiktionary.py
src/wiktextract/wiktwords.py

Because we were using logging.debug, logging.warning and logging.error, our logs are spammed by dependencies that shouldn't be sending debug messages (datetime, apparently).
Hopefully by switching to a instance of Logger instead using root, we can stop those messages.

Switch from root Logger in logging to instance Logger

---

src/wiktextract/logging.py
src/wiktextract/thesaurus.py
src/wiktextract/wiktionary.py
src/wiktextract/wiktwords.py

hide other packages' debug level logs

Only set our `Logger` object's logging level

---

src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/es/translation.py
tests/test_de_page.py
tests/test_es_translation.py

I'll update the mediawiki_langcodes package to add language names and codes in the es edition in case we need these data later.

Get es edition's translation language name from expanded template

---

src/wiktextract/config.py
src/wiktextract/english_words.py
src/wiktextract/extractor/en/page.py
src/wiktextract/form_descriptions.py

Allow more debug messages in extract.errors (I needed some data output by debug messages and spent an embarrassing amount of time trying to find a bug...)
Address some of the bad example classifications in #604.
- "He" was blacklisted as an English word
- Add certain templates to our list of example templates

Classify desc

---

src/wiktextract/extractor/zh/headword_line.py
tests/test_zh_headword.py

Some Japanese header line templates put the `strong` tag inside another `span` tag.

[zh] extract Hiragana data from headword HTML tags

---

src/wiktextract/extractor/zh/page.py

Low quality pages use nonsense language titles. Suppress these check JSON debug messages.

[zh] Set default `lang_code` to `unknown`

---

src/wiktextract/english_words.py
src/wiktextract/extractor/en/page.py
src/wiktextract/form_descriptions.py

Previously, we would expand everything with clean_node and use heuristics to check whether it was an example or not.
However, seeing as how we have access to template
arguments, we can bypass some of these heuristics
early by checking if the text we're checking has
one template, from the example templates set,
with arguments that are the same as what is part
of the clean_node output. In this case, we can just assume this is an example.

Use example template args to determine example

---

src/wiktextract/extractor/ru/page.py

some pages like "Vakuen" put form of template in a list and can't be found by `get_pos()`

[ru] find pos data in form of template name

---

src/wiktextract/extractor/zh/example.py
src/wiktextract/extractor/zh/gloss.py
tests/test_zh_example.py

Some Japanese pages use a separate "ja-x" template in a list under "quote-*" templates.

[zh] extract Japanese example template under "quote-*" template

---

src/wiktextract/extractor/fr/gloss.py
tests/test_fr_gloss.py

Some alt of form templates("variante *") contain the "désuet"("obsolete") tag template.

[fr] remove "désuet" tag template from gloss text

---

src/wiktextract/extractor/en/page.py
usertools/json-check-diffs.py

I've added one more branch to the extract_example multi-line if-tree to account for how `Template:zh-x` formats its examples. Because it's a special case, it's simpler than usual (just using `classify_desc` to put each line into a box).
For example in: https://en.wiktionary.org/wiki/%E6%9C%AA%E9%9B%A8%E7%B6%A2%E7%B9%86
Note that each line is split on square brackets because `[` interferes with `classify_desc`, most probably on purpose (it classifies it as 'other' instead of 'romanization'). `zh-x` uses a lot of "text [Specific Chinese language, trad. or simp.]" style qualifiers, which we're going to ignore and add as part of the text itself. Examples inside senses don't have a `tags` field, and I don't want to add them unless there's a lot more need for it.
The `[` also broke the …

Zhexamples

---

src/wiktextract/extractor/de/flexion.py
src/wiktextract/extractor/de/inflection.py
src/wiktextract/extractor/de/tags.py
src/wiktextract/extractor/zh/section_titles.py
tests/test_de_forms.py

I think `clean_node()` doesn't return the correct string for `[[Flexion:sehend]]`, it returns `sehand` but should be `Flexion:sehend`.

[de] extract verb inflection tables in "Flexion" namespace

---

src/wiktextract/clean.py
tests/test_clean.py

Should only remove "w:" and "s:" prefixes.
Found this wikitext in https://de.wiktionary.org/wiki/Flexion:sehen , remove the namespace causes the de edition code add an extra form data: #644

Don't remove namespace prefix in a link from `clean_value()`

---

src/wiktextract/extractor/zh/etymology.py
src/wiktextract/extractor/zh/example.py
tests/test_zh_etymology.py

most pages uses the ":" list to indent the source example block

[zh] find the "zh-x" template inside list in etymology section

---

src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/pronunciations.py
src/wiktextract/type_utils.py

The code is modified from the zh edition code. The new function adds two tags("Simplified Chinese", "Traditional Chinese") and a new "literal_meaning" JSON field. The literal meaning data is commonly provided in Chengyu pages.
Data are added to `base_data` because "zh-forms" is above POS sections and should be included to all the following POS sections data.
Since the code are mostly the same as the zh edition code, tests are not added.
Example pages:
- https://en.wiktionary.org/wiki/未雨綢繆  (Chengyu, has `lit` parameter)
- https://en.wiktionary.org/wiki/僥倖  (has two POS sections)
GitHub issue #676

[en] extract forms data and literal meaning from "zh-forms" template

---

src/wiktextract/extractor/en/info_templates.py
src/wiktextract/extractor/en/page.py
src/wiktextract/type_utils.py
tests/test_page.py

`info_templates` is similar to etym_templates and
head_templates, but can also have an `extra_data`
field with more specific data relating to the
template in question.
For `+obj`, a vague template that generates text
like `[+accusative]` often meaning 'used with
accusative objects' or `[+dative = means this things]` meaning "if this is with dative it means `this
thing`", but sometimes not, this extra data consists of a `meaning` field from the `means=` parameter,
and `tags` and `words` for parsing the output that isn't the `means=` field.

Add `info_templates` field, handle `Template:+obj`

---

src/wiktextract/extractor/fr/tags.py
src/wiktextract/extractor/ru/gloss.py
src/wiktextract/extractor/ru/linkage.py
tests/test_ru_linkage.py

"семантика" template is used after gloss text to generate linkage sections under gloss lists

[ru] extract linkage data from "семантика" template in sense lists

---

src/wiktextract/extractor/zh/gloss.py
tests/test_zh_gloss.py

The form-of word could be in the first `<i>` tag or the first link.
Previous code use template arguments but some templates like these two don't use the first parameter for language code and get the gloss text for form-of word.

[zh] fix form-of data for "hanja form of", "han tu form of" template

---

src/wiktextract/extractor/fr/models.py
tests/test_fr_etymology.py

This field is only used for matching etymology texts, should be removed from the finally JSON data. "pos_title" is kept in case the POS type is unknown.

[fr] exclude the "pos_id" field from model serialization

---

pyproject.toml

Test files should still be formatted with `ruff format` command, ruff could format long line code.

Add a comment of why ignore E501 rule in tests directory

---

src/wiktextract/english_words.py
src/wiktextract/extractor/de/section_titles.py
src/wiktextract/extractor/es/section_titles.py
src/wiktextract/extractor/fr/section_types.py
src/wiktextract/extractor/ru/section_titles.py
src/wiktextract/extractor/ruby.py
src/wiktextract/extractor/zh/section_titles.py
src/wiktextract/form_descriptions.py
src/wiktextract/translations.py
src/wiktextract/wiktionary.py
src/wiktextract/wiktwords.py
src/wiktextract/wxr_context.py
tests/test_inflection_sh.py

Fixing annotations, mostly.
I've looked a bit at mypy output for the other extractors, and it's helped to find issues with annotations in wikitextprocessor and elsewhere in wiktextract (for example adding some `@overload` stuff). @xxyzz do you mind if I start poking around in there? It should be non-destructive (hopefully).

More cleaning

---

src/wiktextract/extractor/fr/etymology.py
src/wiktextract/extractor/zh/page.py
src/wiktextract/extractor/zh/section_titles.py
tests/test_fr_etymology.py
tests/test_zh_linkage.py

Usually inside a link, but texts are also used.

[fr] find etymology POS title text inside italic node

---

src/wiktextract/english_words.py
src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/ruby.py
tests/test_en_misc.py

Issue #604, Czech translations (continued)
In translations like
```
ví ucho ― Leonotis nepetifolia (literally, “lion's ear”)
```
the translation part starting with "Leonotis" is has its classification returned as "taxonomic" due to the heuristics used in classify_desc().
I've been trying to kludge something better here, but for this specifically the right call to make is to change it so that if a description is either "english" or "taxonomic", that counts as English. There is not meaningful distinction here in the examples when trying to figure out translation stuff.
The heuristics could be better, which is what I tried to figure out, but it works fine for now...

In examples, "taxonomic" is the same as "english"

---

src/wiktextract/extractor/de/example.py
tests/test_de_example.py
tests/test_de_linkages.py

some pages only have example but no gloss, like "60-Jähriger"

[de] add examples that don't have matched gloss

---

src/wiktextract/extractor/en/page.py

An ugly kludge. If there's a `lit=` argument
given to an example template in the `ux` family,
use that when comparing the template arguments
and the initial output.

Handle `lit` arguments in example templates

---

src/wiktextract/extractor/fr/conjugation.py

"fr-conj" shouldn't be used directly but is still used in 19 pages. Also extract "-conj" templates for other languages.

[fr] extract more "*-conj*" templates in "Conjugaison" pages

---

src/wiktextract/form_descriptions.py

Fix #729
These complex regex patterns can't handle nested parentheses in page "Herz" German section's header text.

[en] simplify code removes parentheses text in `parse_word_head()`

---

src/wiktextract/extractor/en/page.py
src/wiktextract/form_descriptions.py
tests/test_classify.py

Add new `accepted` parameter to classify_desc that takes a tuple or frozenset (function is cached) with words that should be accepted by the classifier as `english`.
In en/page.py use data from taxonomy template arguments as accepted words for classify_desc.

Pass data from taxonomy templates to classify_desc for `english` classification

---

src/wiktextract/inflection.py

92 exceptions is not a lot, but enough to stop
the kaikki regen.
This call to unicodedata.normalize() seems to be
the only one that could have had None (others
are either in filtering `if` blocks or would
cause an exception due to the out of bound string
indexing).
I tried to find a final 93rd exception in extract.log (because I got that from `wc -l`) and it was the line "TOO MANY EXCEPTIONS DETECTED"... Which is weird, shouldn't this be in regenerate.log?

Fix exceptions caused by None passed to unicodedata.normalize

---

src/wiktextract/clean.py
tests/test_clean.py

This tag could break HTML tag regex patterns below this line.

Remove `<nowiki/>` in `clean_value()`

---

src/wiktextract/extractor/en/info_templates.py
tests/test_page.py

Template:+obj's output has been changed (and become more complicated), but as a stopgap this should work for a while until more complex stuff emerges in actual practice.
Remove the literal plus "\+" from the regex, that's been removed; for the purposes of +obj, I think every output starts with `[with`, but there might also be `along with` and `and` in the mix somehow.
Clean the template output value of all the style pseudo-HTML wikitext elements and other HTML stuff.

Synch with changes to Template:+obj

---

src/wiktextract/extractor/pl/inflection.py
src/wiktextract/extractor/pl/tags.py
tests/test_pl_inflection.py

I though pl edition has two more forms tables then en edition but en edition has the same tables in the comparative form page, pl edition puts all tables to the base word page.

[pl] extract adj forms table "odmiana-przymiotnik-polski" template

---

src/wiktextract/extractor/zh/descendant.py
src/wiktextract/extractor/zh/inflection.py
src/wiktextract/extractor/zh/note.py
src/wiktextract/extractor/zh/translation.py
tests/test_zh_descendant.py
tests/test_zh_etymology.py
tests/test_zh_example.py
tests/test_zh_gloss.py
tests/test_zh_headword.py
tests/test_zh_inflection.py
tests/test_zh_linkage.py
tests/test_zh_note.py
tests/test_zh_pronunciation.py
tests/test_zh_thesaurus.py
tests/test_zh_translation.py

Some pages only have two columns, `zip_longest` will use `None` causes the error. Check `<span>` tag's class name to find roman data.
Remove simplified test `test_ja_i_template` that doesn't have `span` tag.

[zh] fix pydantic error in `extract_ja_inf_table()`

---

src/wiktextract/extractor/zh/inflection.py
tests/test_zh_inflection.py

skip empty rows and use cell node as header node if is has bold node

[zh] fix the rest pydantic errors in `extract_ja_inf_table()`

---

src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/pronunciation.py
tests/test_en_pronunciation.py

Should fix #... Actually, this was an e-mail issue.
We have examples of pronunciation sections like English ["past"](https://en.wiktionary.org/wiki/past#Pronunciation):
`===Pronunciation===`
* ([Received Pronunciation](https://en.wikipedia.org/wiki/Received_Pronunciation)) [enPR](https://en.wiktionary.org/wiki/Appendix:English_pronunciation): päst, [IPA](https://en.wiktionary.org/wiki/Wiktionary:International_Phonetic_Alphabet)([key](https://en.wiktionary.org/wiki/Appendix:English_pronunciation)): /pɑːst/
where the first parenthetical tags also obviously apply to other entries or templates on the same line.
This ended up as a bigger project than I thought, but it should be a bit better.
I will write some more tests tomorrow, I just want this uploaded for now.

[en] Changes to en/pronunciation.py; clean up template parsing, push earlier tags on the same line

---

src/wiktextract/extractor/en/section_titles.py
src/wiktextract/parts_of_speech.py

Some Korean entries depend on this.
Fixes #790
Added to both parts_of_speech and POS_TITLES in extractor/ en/section_titles... Should clean this up, or import parts_of_speech into section_titles.

Add "Dependent noun" as POS

---

src/wiktextract/extractor/en/section_titles.py
src/wiktextract/parts_of_speech.py

Some Japanese entries depend on this, such as [この](https://en.wiktionary.org/wiki/%E3%81%93%E3%81%AE).

Add "adnominal" as POS

---

src/wiktextract/data/zh/config.json

page "Appendix:Glossary" is used in "Module:Glossary/data"
Fix many Lua errors...

[zh] add "Appendix" namespace pages

---

src/wiktextract/extractor/en/example.py
src/wiktextract/extractor/en/page.py
src/wiktextract/type_utils.py

Most code are copied from zh edition code with some modifications.
Separate Traditional Chinese, Simplified Chinese, dialect and other tag properly.
Also handle the common "zh-x" and "ja-x" template under "quote-*" template layout.
Example pages: [大家](https://en.wiktionary.org/wiki/%E5%A4%A7%E5%AE%B6), [尋釁滋事](https://en.wiktionary.org/wiki/%E5%B0%8B%E9%87%81%E6%BB%8B%E4%BA%8B)
The code could also be reused for example templates in Chengyu pages, like [買櫝還珠](https://en.wiktionary.org/wiki/%E8%B2%B7%E6%AB%9D%E9%82%84%E7%8F%A0)

[en] extract "zh-x" example templates properly

---

src/wiktextract/extractor/pl/models.py
src/wiktextract/extractor/pl/translation.py
tests/test_pl_translation.py

and combine links next to each other to one word
The "furi" template doesn't expand to `ruby` tags like other editions.

[pl] extract "furi" Japanese templates in translation lists

---

src/wiktextract/extractor/en/example.py
src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/zh/example.py

Similar to zh commit 4468de7, there is a small difference in expanded HTML nodes: "trad." and "simp." links after example text are inside an `<i>` tag, zh edition doesn't have it.
Test was added in the zh edition commit, I also tested some pages locally.

[en] don't extract "span" tag in example source "dd" tags

---

src/wiktextract/extractor/de/example.py
src/wiktextract/extractor/de/models.py
tests/test_de_example.py

Same as other editions.
And limit extract example reference template args to "Literatur" template, currently there are too many debug message of unknown args and it's a maintenance nightmare to track all these templates.

[de] rename `Example`'s "raw_ref" field to "ref"

---

src/wiktextract/clean.py
tests/test_clean.py
tests/test_en_page.py

Can't find any easy documentation, but wikitext behavior seems to be that if there is any whitespace, including newlines, before a [[Category:...]] link that is not a "displayed" [[:Category:...]] link, all whitespace before that is stripped away. So:
```
foo
[[Category:test]]bar
```
becomes `foobar`.

clean_value: Remove whitespace before Category links

---

src/wiktextract/extractor/fr/conjugation.py

Template parameter is not always a list, a template could be written in a single line.
Fix error in page "Conjugaison:français/bastinguer".

[fr] fix `TypeError: 'TemplateNode' object is not iterable`

---

.github/workflows/test.yml
.github/workflows/test_schedule.yml
pyproject.toml

Only create test coverage for 3.11, it's slow on 3.12 and 3.13.

Add Python 3.13 test action

---

src/wiktextract/extractor/en/page.py
tests/test_en_page.py

Fixing an oversight where `form_of` was left out in certain situations.

[en] Add `form_of` fields to subglosses more consistently

---

src/wiktextract/extractor/es/example.py
tests/test_es_example.py

this template doesn't expand to HTML tags if source parameters are not used, fix #880

[es] extract example text in "ejemplo" template's first parameter

---

src/wiktextract/wiktionary.py

too many this kind of messages bury the real check JSON messages
`valid_tags` and `uppercase_tags` global variables should use uppercase, but en code import them in many places and website code could also be affected so I didn't rename them.

[en] silence invalid uppercase tag check JSON debug messages

---

src/wiktextract/extractor/en/form_descriptions.py
src/wiktextract/tags.py
tests/test_en_tags.py

Removed unused code with `valid_words` from 2020. Didn't find an elegant way to use it where it was meant to be used.
I've been hitting my head trying to figure out what to do in decode_tags1 to get " and " to parse correctly (that is, ignored it), and finally gave up. Instead, I've implemented a new kludge in the vein of the "/"- kludge preceding this, except thankfully simpler.
Fixes #891

[en] Retry decoding tags with errors if " and " in tag

---

src/wiktextract/extractor/nl/inflection.py
src/wiktextract/extractor/nl/page.py
src/wiktextract/extractor/nl/section_titles.py
src/wiktextract/extractor/nl/tags.py

"-nlnoun-" template doc doesn't say the fifth param is used in table header if provided

[nl] fix `AttributeError` in page "Waal"

---

README.md

Changed http:// to https:// and removed the space halfway through the link so that it renders properly.

Fix README.MD typo

---

src/wiktextract/extractor/nl/analyze_template.py
src/wiktextract/extractor/nl/example.py
src/wiktextract/extractor/nl/inflection.py
src/wiktextract/extractor/nl/pos.py
src/wiktextract/extractor/nl/tags.py
tests/test_nl_gloss.py

The last commit is a temporary workaround to remove double underscores magic word before level nodes in some templates, I think this should be implemented in wikitextprocessor package(allow magic word before level node) but I'm not sure whether it's a trivial change.

[nl] improve extract pos section code

---

src/wiktextract/extractor/en/inflection.py
src/wiktextract/extractor/en/page.py

März/German 20241111
```
====Declension====
{{de-ndecl|m,-[predominant]:es[less common]}}
; Obsolete declension:
{{de-ndecl|m.weak}}
```
Previously, the definition list (WHICH SHOULD NOT BE USED FOR BOLDING/FORMATTING ACCORDING TO WIKITEXT GUIDELINES) was attached to the preceding template, instead of starting a new section.
Changes include: special handling for `;` lists in inflection sections, using the contents of those bolded lists as a title for the following template, and a new tagged title string in tags.py
Fixes #903

[en] Handle German tables preceded by a ";" list

---

src/wiktextract/extractor/en/page.py

Fixes #910
Files are links, and so if they have an alt-text that alt-text would pop up in heads because we handle En heads by looking at the nodes and don't use clean_value.
We might want to consider creating a LinkNode and FileLinkNode class like we have for TemplateNode so that we can more easily filter out file links.

[en] Filter out LINK nodes that are files from headers

---

src/wiktextract/extractor/en/example.py
src/wiktextract/extractor/en/form_descriptions.py
src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/type_utils.py
src/wiktextract/tags.py
tests/test_en_head.py

#906
Not sure if this is the correct fix.

[en] don't extract converted topic data as form

---

src/wiktextract/extractor/en/page.py

I forgot Python strip() takes a string of characters, which are all stripped from both ends.

[en] No need to use .strip() chaining

---

src/wiktextract/extractor/en/page.py

Check if link.largs[0][0] is a string.

[en] Fixed exception when link is broken

---

src/wiktextract/extractor/de/models.py
src/wiktextract/extractor/de/page.py
src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/de/tags.py
tests/test_de_example.py
tests/test_de_gloss.py
tests/test_de_pronunciation.py

[de] extract nested sound lists

---

src/wiktextract/config.py
src/wiktextract/data/pt/config.json
src/wiktextract/extractor/de/pronunciation.py
src/wiktextract/extractor/pt/models.py
src/wiktextract/extractor/pt/page.py
src/wiktextract/extractor/pt/pos.py
src/wiktextract/wiktwords.py
tests/test_pt_gloss.py

Requires https://github.com/tatuylonen/wikitextprocessor/pull/348
also only use `template_override_fns` for en edition, not sure if these functions are still needed, I think they could also be overridden in the "src/wiktextract/data/overrides" folder.

[pt] add parser function aliases configurations

---

src/wiktextract/extractor/en/form_descriptions.py

Fixes #983: "present participle Martinize" was interpreted as tags ["present"] and the form "participle Martinize".
This was because the code at:
```python
if (
i > 1
and len(parts[i - 1]) >= 4
and distw(titleparts, parts[i - 1]) <= 0.4
):
alt_related = related
alt_tagsets = tagsets
continue
```
would see that "participle" is very close (exactly 0.4) in distw() Levenshtein distance to "Martinize" and accepted that it must be part of the titleparts
list, like a word in a phrase.
This kludge just adds a test to see if titleparts is shorter than the rest of `parts`, don't do that.
THIS WILL FAIL IN CERTAIN SCENARIOS, like when an
'inflected' form gains more words!

[en] Form descriptions: check if a 'form' has too many words

---

README.md

it's not an optional argument for non-English editions

Add "--edition" option to command line examples

---

src/wiktextract/extractor/en/form_descriptions.py
tests/test_en_head.py

"clipping" was skipped because it had too high distw() with "clip" (0.5), so I added yet another kludge for when the language section is English: if something starts with the title, accept it in this case. This will cause problems elsewhere, but we'll hunt those down...
Fixes #967

[en] Adjustment to form_description heuristics

---

src/wiktextract/extractor/en/form_descriptions.py
tests/test_en_head.py

Issue #967
In cases like "clipping" missing from the `forms` data for "clip", because of one reason or another the loop skips that section of the head forms, we instead check if the language is English and whether the article and the form are in a dict and let them through if so.
We also introduce a new debug message that warns when there seems like there should be a form with certain specific head-specific tags like "plural" or "present" or "participle". Empty cases cannot be reported because that would hit every "uncountable," style higher-level tag.

[en] Complicated case-by-case handling of missing forms

---

src/wiktextract/extractor/en/page.py

https://stackoverflow.com/q/10742501
This is very helpful for hunting down forgotten prints.
I first tried to use pbd and `break print` to make a breakpoint on `print()` calls, but that doesn't
work for builtins, but the above Stackoverflow question had a suggestion that worked out. Just add the class and the code into wiktwords and reassign `sys.stdout` in `main()`, and it will at least tell you the
function that is generating the print.

[en] Disable stray debug print; learned a new Python trick

---

src/wiktextract/extractor/en/inflection.py
src/wiktextract/extractor/en/inflectiondata.py
src/wiktextract/extractor/en/page.py
tests/test_en_inflection_aii.py

At some point, having several templates in an inflection section needed to be fixed, which I think I? did with a simple regex for curly braces and matching nesting levels.
However, in cases where you got already pre-expanded (or just raw wikitext) tables in the inflection section instead of templates, this broke down the table when encountering templates inside the table.
This should fix #973 
The issue was the introduction of new inflection-table-top and inflection-table-bottom book-end templates, similarly to how trans-top and trans-bottom are used to generate large translation sections. These generate warning messages because they create dangling HTML tags and other nasty stuff, but as long as they're pre-expanded it should be fine... Except it exposed a previous bug as detailed above. …

Fix pre-expanded templates being split by inflection section template detection

---

src/wiktextract/extractor/en/page.py

Turns out this was unnecessary, I just missed it
because I didn't test whether it was necessary.
These two templates are already put under pre-expand due to automatic heuristics.

[en] Remove unnecessary pre-expand directive

---

src/wiktextract/extractor/en/form_descriptions.py
src/wiktextract/extractor/en/page.py

Just to get rid of some unnecessary debug messages, `also` was previously ignored but not its subpages.

[en] Ignore "also/..." templates like "also" is ignored

---

src/wiktextract/categories.py
src/wiktextract/wiktwords.py

One of the "Module:category tree/poscatboiler/data" subpage has a string type `v.parents`.

[en] fix Lua error and `IndexError` exception in categories.py

---

src/wiktextract/extractor/th/linkage.py

page "ขาว" uses it's antonym's thesaurus page for antonym data, which also uses "ขาว"'s thesaurus page for antonym section.

[th] fix `RecursionError` in some thesaurus pages

---

src/wiktextract/extractor/en/page.py

GH issue #973
pre-expanded "aii-infl-prep/1c" template can't be processed by `inflection_template_fn()` and "at-prep-auto" can't be matched by the template name regex pattern.

[en] add "aii-infl-prep/1c" and "at-prep-auto" templates to "inflection_templates"

---

src/wiktextract/extractor/en/page.py

GH issue https://github.com/tatuylonen/wiktextract/issues/973
Related PR https://github.com/tatuylonen/wiktextract/pull/1030
There's a lot aii templates which are afflicted by this issue and imo it's better if it works for all or none - otherwise it creates some confusion

[en] remove "aii-infl-prep/1c" from "inflection_templates"

---

src/wiktextract/extractor/en/form_descriptions.py
src/wiktextract/extractor/en/page.py
tests/test_en_head.py

Aii, aii, aii. At first I thought the issues was regex (and it can be, but not specifically here).
Fixes #1034
This is because of a kludge I had where I added problematic article titles to a list `links` containing words taken from links in the head, which would then be added to the default regex as "words".
The issue here was that the dash at the start of the articles (because they're suffixes) caused the article title to be added to `links`, but the articles did not have the *combining diacritic* that the form *did* have. So the regex had a "word" that overrode the actual good behavior, and it would split the form into two: the first characters from the article title and then a combining diacritic (+ rest if any).
This cannot be fixed in regex with `\b` (word-boundary virtual character …

Aii extra space

---

pyproject.toml

- `project.license` as a TOML table is deprecated
- License classifiers are deprecated

Fix two `SetuptoolsDeprecationWarning`

---

src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/section_titles.py

See: mouth, heath, town
If we have a section like
```
====Derived terms====
* {{lookfrom|en|town}}
=====Nouns=====
...
=====Proper nouns=====
...
```
fix_subtitle_hierarchy will demote "Derived Terms" to level 6 (due to moving all Pronunciation sections between 3 and 4) and so `Nouns` and `Proper Nouns` are at the same level and don't get parsed at all.
Fix: make section titles "nouns" and "proper nouns" into linkage section names. This seems to be the case in the database currently, "Nouns" and "Proper nouns" are not used as POS sections.

[en] Add "Nouns" and "Proper Nouns" linkage section titles

---

src/wiktextract/extractor/en/example.py
src/wiktextract/extractor/en/type_utils.py
src/wiktextract/extractor/fr/gloss.py
src/wiktextract/extractor/fr/models.py
src/wiktextract/extractor/share.py
src/wiktextract/extractor/zh/example.py
src/wiktextract/extractor/zh/models.py
tests/test_en_category.py
tests/test_en_pronunciation.py
tests/test_fr_gloss.py
tests/test_fr_linkage.py
tests/test_zh_etymology.py
tests/test_zh_example.py

#1071
Some templates expand to evil wikitext like `[[焚#Chinese|<b>焚]][[膏油#Chinese|膏</b>油]]` in page [焚膏繼晷](https://en.wiktionary.org/wiki/%E7%84%9A%E8%86%8F%E7%B9%BC%E6%99%B7), and our code can't handle this kind of node structure. Better fix the template Lua code on Wiktionary.

[en, fr, zh] add example bold word offsets data

---

src/wiktextract/extractor/en/page.py

Fixes some issues, for example see ܒܝܬ ܢܗܪܝܢ/Assyrian Neo- Aramaic.
These templates (which find sense data by id from other articles) create lists (of glosses, typically) that are turned into lists too late and thus get lumped under one gloss entry.

[en] Pre-expand `Template:transclude`

---

src/wiktextract/extractor/en/example.py

same Lua module, resolve #1119

[en] extract "uxa" example template as "ux" template

---

src/wiktextract/extractor/el/models.py
src/wiktextract/extractor/el/pos.py
src/wiktextract/extractor/el/tags_utils.py
tests/test_el_form_of.py
tests/test_el_inflection.py

Closes #1122
This should cover most nouns and adjectives.
Notes:
- Glosses are unchanged based on this [structure]
(https://github.com/tatuylonen/wiktextract/issues/1122#issuecomment-2803472770).
- Glosses are not tested in order to avoid expanding templates. I did verify locally that indeed they were unaffected by the changes.
- Some `raw_tags` (cf. θηλυκό) are parsed from `raw_tags` into `tags` at some other points of the code. I didn't add any extra logic myself.
- I didn't see how to apply @xxyzz [comment](https://github.com/tatuylonen/wiktextract/issues/1122#issuecomment-2800936424). Everything is done at `parse_gloss_inflections`.
Let me know what you think.

[el] add form_of parsing for inflections (nouns, adjectives)

---

src/wiktextract/extractor/en/page.py

fix #1149
should use the more relaxed "re.search" as previous code

[en] match "*-suffix-noun" POS header templates

---

src/wiktextract/extractor/fr/page.py

page "gueule cassée" has an incorrect ":" note list

[fr] only process "#" list as gloss list

---

src/wiktextract/extractor/el/pos.py

Fixes #1185
Some word entries just use a pseudo-gloss with ":" and a "see x"-template, with nothing else. If we find something that at first doesn't seem to have any glosses, check it again and accept `:` lists.

[el] Some stupid code-duplication to recheck for glosses

---

src/wiktextract/extractor/el/page.py
src/wiktextract/extractor/el/pos.py
tests/test_el_form_of.py

Support extracting the `form_of` for the [κλ](https://el.wiktionary.org/wiki/Πρότυπο:κλ) generic (noun, verbs etc.) template.
Fixed a couple typos too, and updated the documentation.
The git diff is a bit loud because my formatter didn't like the wxr warnings in two lines.
Also I am not sure what the `sortid` of the warnings accomplishes, I just copied the one a couple lines below. Let me know if I should change it.

[el] Support `form_of` for `κλ` template

---

src/wiktextract/extractor/el/pos.py
tests/test_el_form_of.py

This requires a bit of grammar explanation. I'll try to be succint.
I will probably butcher some terms, so bear with me.
Every Greek verb (take `λέω`, to say) uses the perfective form (`πω`) for both simple future and subjunctive. The only way to distinguish both is by looking at the previous particle. `θα πω` (= I will say) / `να πω` (not really translatable, but when found alone, it is something like ~let me say). Not much unlike in English `I will say` / `I would say` requires you to look at the previous particle and not only the verb inflection.
Now, for some reason, the wiktionary editors decided to repeat this "rule" at every entry, even though it is not something that depends on the verb, identically to what happens in English.
You can find, for example …

[el] Support `ρημ τύπος` template when prefixed by "junk"

---

src/wiktextract/extractor/el/pos.py
tests/test_el_glosses.py

The test should be self explanatory.
Note that the `πτώσεις` template transpiles to the glosses. This is fine and coherent with the tests in `test_el_form_of.py`. The glosses just happen to be hidden there. Compare the results from a word in that test suite with the newly added `επωτίδες`:
```JSONL
{"word":"κόρφο","lang_code":"el","lang":"Greek","pos":"noun","senses":[{"glosses":["αιτιατική ενικού του κόρφος"],"tags":["accusative","singular"],"form_of":[{"word":"κόρφος"}]}]}
{"word":"επωτίδες","lang_code":"el","lang":"Greek","pos":"noun","senses":[{"glosses":["ονομαστική, αιτιατική και κλητική πληθυντικού του επωτίδα"],"tags":["accusative","nominative","plural","vocative"],"form_of":[{"word":"επωτίδα"}],"related":[{"word":"ἐπωτίδες"}]}]}
```

[el] Extract `form_of` when there are more than one template in contents

---

src/wiktextract/extractor/en/inflection.py
src/wiktextract/tags.py
tests/test_en_inflection_en.py

There are tables that mix td-elements and wikitext table syntax.
This is most probably done because it doesn't matter in Wikitext
whether something is a wikitext table or HTML-element, they
all get expanded into HTML eventually.
However, it wreaks havoc on our parse-tree, because in these
cases td-elements are made into the direct children of a
TABLE_HEADER or TABLE_CELL node, when they should be "siblings".
td-elements are mixed into Wikitext tables probably? because
they're easier to write #if-conditions etc. for. Just clearer,
in wikitext.
Instead of "correctly" parsing this (which is contradictory:
there might not be a 'correct' way to do this), we instead
correct for this in code by checking if a `col` node's children
include direct child td-elements, and yield those, too.
#1196 …

[en] Yield td-elements that are erroneously children of TABLE_CELL

---

src/wiktextract/extractor/el/pos.py
tests/test_el_form_of.py

Support `form_of` for the [participle](https://el.wiktionary.org/wiki/Κατηγορία:Πρότυπα_για_μετοχές) (μετοχή) template family.

[el] Support `form_of` for participles

---

src/wiktextract/extractor/ru/inflection.py
src/wiktextract/extractor/ru/page.py
tests/test_ru_gloss.py
tests/test_ru_inflection.py

use expanded nodes, template args are unreliable, fix #1212

[ru] extract comparative forms data in "прил ru*" templates

---

src/wiktextract/extractor/el/pos.py
tests/test_el_glosses.py

When recursing down the list, bubble up with separate lists of things. If there is a list of Senses, return those; if there are other things, like examples or synonyms etc. attach them to the gloss at the current level, if applicable.
Takes care of #1199

[el] Improve recursive sense list parsing

---

src/wiktextract/extractor/en/example.py
src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/type_utils.py
src/wiktextract/tags.py

This took me far too long to figure out the correct way to do it. Fixes #1263

[en] Fix templates `cot` and `alti` being interpreted as examples

---

src/wiktextract/extractor/en/pronunciation.py
src/wiktextract/extractor/en/type_utils.py
tests/test_en_pronunciation.py

Instead of having a field `hyphenation` (which should be deprecated) with a list of strings, this introduces a new Hyphenation TypeDict with a `parts: list[str]` field for the different parts of a hyphenation and `tags`.
Currently we will have these two parallel and try to remove `hyphenation` later.
`hyphenation` and `hyph` templates are also handled now in the template-handling function in pronunciation.py, in a similar way to pron and audio file templates.
However, some language-specific templates have their own modules that generate their own hyphenation text (looking at you, it-pr...) so this won't handle that.
"Why doesn't this Italian language example work?? Wait, `quieto` doesn't use `hyph` like the template documentation example said, it uses its own template..."

[en] Introduce `hyphenations` field, handle `hyph` template

---

src/wiktextract/extractor/en/pronunciation.py
tests/test_en_pronunciation.py

Fixes #1246 
Should take care of most arbitrary hyphenation sections found in stuff like templates generated by modules, etc. Basically, it's the backup for when `hyph` is not used and we end up with just raw text hyphenation data.

[en] Improve hyphenation code for arbitrary hyphenation in text

---

src/wiktextract/extractor/en/page.py
tests/test_en_pronunciation.py

the two POS sections under two pronunciation sections should have different "sounds" data
the second test is for commit 24b7d98 which added the `inside_level_four` variable
I don't know whether the change make sense but it passes the tests...

[en] fix pronunciation data in page "大家"

---

src/wiktextract/extractor/en/page.py
src/wiktextract/extractor/en/type_utils.py
src/wiktextract/tags.py
tests/test_en_page.py

Issue #1278
Done within the gloss/sense template handler function.
`Template:defdate` is used to show the earliest (or just early) attested dates in text where a word, or a word sense, has been found. It's main parameter (#1) is a string data like "early 19th century", and it can have up to three `refX=` and `refXn=` arguments. The ref (based on how it's in etymology templates) is probably a `Template:ref` style reference that is then output by the Wiktionary expander with a `<references/>` tag later in the article, while the `refn` arguments refer to these without repeating the `ref` part. I think, based on a quick look, that we don't do special reference handling with `ref` template data, but the same data can be found within the word data so users should be able to access it.
For …

[en] Add "attestations" field to senses (Template:defdate)

---

src/wiktextract/extractor/en/inflection.py
src/wiktextract/tags.py

Reverts PR #1323
Even though there's nothing "wrong" with the actual code changes, except a minor resource cost because we do more things, if it's not actually needed I decided to revert it.
The actual "fix" to this seems to be that when parsing the output of tables, we do some bespoke local recursive delving of the parse tree for some reason (probably makes sense), so `clean_node()` is not actually used here to get the `after` text of the table containing footnotes.
Solution: when recursing, skip `ref`-elements.
The broken ref-less version of the taggable string text that was problematic was move from `xlat_descs_map` to normal tags.

[en] Revert changes to `add_def`, remove ref-elements in `after`

---

src/wiktextract/extractor/ja/translation.py

a redirect page title is used in "trans-see" template and the redirected page doesn't have translation section

[ja] fix `AssertionError` exception in page "ドライバー"

---

src/wiktextract/extractor/en/inflection.py
src/wiktextract/extractor/en/inflection_kludges.py

See #1286#issuecomment-3280297085
The previous kludge assumed this table would only have one entry per cell of Georgian+romanization, with alternative forms shown with suffixes in parentheses (suffix and no suffix), but turns out these can be comma-separated alts.
The comma separated alts are already separated earlier in the text, so we only need to loop over them (and also check the length of `alts` with `>= 1` instead of `== 1`...).

[en] Georgian ka-decl-noun kludge extended to comma-separated alts

---

src/wiktextract/extractor/en/inflection.py
src/wiktextract/tags.py

I noticed that in the ancient Greek entries, the only dialects that were being included in the table tags were `Attic` and `Epic`, for example the [JSON](https://kaikki.org/dictionary/Ancient%20Greek/meaning/%CE%B2/%CE%B2%CE%B1/%CE%B2%CE%B1%CE%B8%CF%8D%CF%82.html) for [βαθύς](https://en.wiktionary.org/wiki/%CE%B2%CE%B1%CE%B8%CF%8D%CF%82#Ancient_Greek) includes:
```json
{
"form": "Attic declension-3",
"source": "declension",
"tags": [
"table-tags"
]
},
```
```json
{
"form": "Epic declension-3",
"source": "declension",
"tags": [
"table-tags"
]
},
```
but does not include `"form": "Byzantine declension-3",`.
I'm not completely sure that this is how the code works, so there may be mistakes in the pull request. What I've done is add all of the other dialects to the two places in the code where …

[en] Include missing ancient Greek dialects

---

src/wiktextract/extractor/el/etymology.py
src/wiktextract/extractor/el/models.py
src/wiktextract/extractor/el/page.py
src/wiktextract/extractor/el/pos.py
tests/test_el_etymology.py
tests/test_el_form_of.py

Should fix most of the stuff in #1372

[el] `form_of` templates: handle bad templates and also extract from etymology

---

src/wiktextract/thesaurus.py
src/wiktextract/wiktionary.py

"forkserver" is faster than "spawn" and is the default method since Python 3.14

Change process start method to "forkserver"

---

src/wiktextract/extractor/el/pos.py
tests/test_el_form_of.py

Add `form_of` for this template: [γρ](https://el.wiktionary.org/wiki/Module:%CE%AC%CE%BB%CE%BB%CE%B7%CE%BC%CE%BF%CF%81%CF%86%CE%AE)
The code would have been simpler if I didn't observe some users doing questionable things with the template. In their defense, the template documentation could have been clearer. It mixes alternatives writings with forms of, their example is completely wrong, it works when it should not, etc.
Nevertheless, in my experience this makes sense, and follows the same logic as the other `form_of` templates.
There is some noise due to my formatter. I hope that's not a problem.

[el] Support `form_of` for `γρ` template
